### ISSUE TITLE
CryptoExchange.Net work with MetaTrader 5/4 servers in the Future?

### ISSUE THREAD

**Issue by dante1989** [JKorf/CryptoExchange.Net#101]
As you know, Forex brokers now support Many Stocks and Cryptos like (BTC, ETH,...) allowing trading as CFDs. And most Forex brokers are supporting MT5/MT4 terminal to create Bot and run Bot on MT5/MT4 terminal. However, I am personally a programmer only familiar with VB.Net and C#.NET
Currently, I want to create a new bot having API works directly with MetaTrader 5 and 4 servers (No need to run Metatrader terminal. No need to install server side plugins. API simply emulates MT4/5 terminal and works with server by TCP. Able to connect to any server. MT4/MT5 API developed purely on .NET and ready for cross-platform DotNET Core applications). For exampke, get candlestick data from mt5/mt4 servers to analyze and place orders but still run on VB.Net or C#.Net.
Are you planning to develop MT5.Net or MT4.net based on CryptoExchange.Net platform?
Some parties have successfully done API (MT5-MT4) for .NET like that, but they do not make professional and scientific API like yours.
If possible, I will be the first person to support you with at least 3000 USDT or more for your efforts. This is very useful for Traders who are familiar with .NET and are trading Stocks and Cryptos (CFDs) on Forex brokers. Thank you for listening

**Comment by JKorf** [comment]
Sorry Dante, I totally forgot to answer to this. I did think about it, and although your offer of support is generous I don't think the library is fit for implementing a different way of communication. Also, I'm not familiar at all with the protocol used by MetaTrader at all. 
For now I don't see this happening, though maybe I'll reconsider at some point in the future.
