### ISSUE TITLE
Request for info in IExchangeClient.PlaceOrderAsync 

### ISSUE THREAD

**Issue by heavymanto** [JKorf/CryptoExchange.Net#102]
I would like to open an order at market price, without specifying take profit or stop loss. An algorithm studies the market and at some point decides to close the order(s). After placing the order with IExchangeClient.PlaceOrderAsync how can I give the close command? thank you

**Comment by JKorf** [comment]
On spot API the process is normally this:
Open position: PlaceOrder(buy)
Close Position: PlaceOrder(sell)
Just place a new sell order for the amount that you bought.
