### ISSUE TITLE
Replace AutoResetEvent in SendLoopAsync by AutoRsetEventAsync from Stephen Toub

### ISSUE THREAD

**Issue by EricGarnier** [JKorf/CryptoExchange.Net#110]
Hi JKorf,
I notice that in the sendloop, you use an AutoResetEvent. As this loop call async method (Task.Delay and SendAsync), the execution can move from one thread to another. In this case, the waiting on the AutoresetEvent can block an other task in the system.
I suggest that you replace this by the AutoRsetEventAsync from Stephen Toub [https://devblogs.microsoft.com/pfxteam/building-async-coordination-primitives-part-2-asyncautoresetevent/](https://devblogs.microsoft.com/pfxteam/building-async-coordination-primitives-part-2-asyncautoresetevent/)

If you agree, I can produce a PR for this.
Thanks
Eric

**Comment by JKorf** [comment]
Hi, there is already an extension method for a WaitHandle to be async awaited available in CryptoExchange.Net. I've changed the send loop to use that, so that should fix the potential blocking. Can you have a look at 29ebd139588dd2f8a4c6fbcc9219357e33967c1a and see if you agree?

**Comment by EricGarnier** [comment]
Perfect.

Eric

De : Jan Korf ***@***.***>
Envoyé : Thursday, September 23, 2021 3:07 PM
À : JKorf/CryptoExchange.Net ***@***.***>
Cc : EricGarnier ***@***.***>; Author ***@***.***>
Objet : Re: [JKorf/CryptoExchange.Net] Replace AutoResetEvent in SendLoopAsync by AutoRsetEventAsync from Stephen Toub (#110)


Hi, there is already an extension method for a WaitHandle to be async awaited available in CryptoExchange.Net. I've changed the send loop to use that, so that should fix the potential blocking. Can you have a look at 29ebd13<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJKorf%2FCryptoExchange.Net%2Fcommit%2F29ebd139588dd2f8a4c6fbcc9219357e33967c1a&data=04%7C01%7C%7C1044fdd15af349b4c80708d97e92fc03%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637679992025505329%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=fGjwIPj2NMx89sfDO1CfYkofuXjhAJs4wrU5sbYdFV8%3D&reserved=0> and see if you agree?

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJKorf%2FCryptoExchange.Net%2Fissues%2F110%23issuecomment-925799221&data=04%7C01%7C%7C1044fdd15af349b4c80708d97e92fc03%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637679992025515317%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=w72EyZRrFxz7J3%2Fh%2FvDyF50k1%2BD5w0Aut62tm6wHV7E%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFLW7FPJSRO4Y65Q5MJXKFLUDMQ6BANCNFSM5ETRFVUQ&data=04%7C01%7C%7C1044fdd15af349b4c80708d97e92fc03%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637679992025515317%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=bYezMP4TpbUTN9kIDQMujIQVMshT0lqXBFic%2BQg2X4A%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C1044fdd15af349b4c80708d97e92fc03%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637679992025525312%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=BBVMxP3yfcrgDN0x81m%2BskIS%2BJbvzNYYYJxPn2FObQM%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C1044fdd15af349b4c80708d97e92fc03%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637679992025525312%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xapYNdBn6LadJmwi6sYs1ddlorzKB8%2FM%2Flkb0Y94MpA%3D&reserved=0>.
