### ISSUE TITLE
Bug in RestClient.ConstructRequest

### ISSUE THREAD

**Issue by gensleralexander** [JKorf/CryptoExchange.Net#114]
Hello,

in RestClient.cs, Line 376-378 you have:
https://github.com/JKorf/CryptoExchange.Net/blob/ac269e8368842da0e82d9038a8dcb3e2ae622a41/CryptoExchange.Net/RestClient.cs#L376-L378

Last line should be:
`request.Accept = contentType; `
because otherwise you'll never accept FormContent. Or am I missing something?

Greetings
Alexander

**Comment by gensleralexander** [comment]
Is there anyway to configure the request, to accept FormContent? I want to query Bitstamp API that uses FormContent.

**Comment by JKorf** [comment]
The Bitstamp API as described here https://www.bitstamp.net/api/ seems to be returning json. Am I missing something?

**Comment by gensleralexander** [comment]
Oh sorry, my mistake, you are right. Only the POST is in FormContent, but not the response.
