### ISSUE TITLE
Post/Delete request without parameters ignores header 

### ISSUE THREAD

**Issue by valvv** [JKorf/CryptoExchange.Net#117]
New bug fot 4.2, it works in 4.0 and below

RestClient.ConstructResult: line 403
if (parameterPosition == HttpMethodParameterPosition.InBody)
{
-->   if (parameters?.Any() == true)
              WriteParamBody(request, parameters, contentType);
        else
                request.SetContent(requestBodyEmptyContent, contentType);

If parameters list is empty, it ignores request headers
Some exchanges required empty DELETE post, like this
DELETE /api/v1/orders/{orderId}

**Comment by valvv** [comment]
I thinks the fix is if (parameters?.Any() == true ||  signed)

**Comment by JKorf** [comment]
Request headers aren't written at all in the part of the code you linked, apart from the Content-Type header which is set regardless of the if statement.
What header are you missing in which library?
