### ISSUE TITLE
Need an extra QueryAsync method for Socket Client

### ISSUE THREAD

**Issue by burakoner** [JKorf/CryptoExchange.Net#118]
**Describe the bug**
OKEx(and some other exchanges) needs to ping-pong mechanism to survive. If you dont send ping, exchange disconnects you. So I decided to send ping request with a timer. It sounds good but not. Because there can be multiple socket connections. 

**Expected behavior**
So I need to get all active socket connections and send ping request for each one. This algorithm needs an extra QueryAsync method with signature below
```C#
protected virtual Task<CallResult<T>> QueryAsync<T>(SocketConnection socketConnection, object request)
```

This provides me freedom that I can choose which socket connection to send query.

I'll be pleased if you add this method.

Have a nice day

**Comment by JKorf** [comment]
I think you can use the `SendPeriodic` method right? 
For example CoinEx also needs a ping request, and this sends it every minute:
````C#
public CoinExSocketClientSpot(CoinExSocketClientSpotOptions options) : base("CoinEx", options, options.ApiCredentials == null ? null : new CoinExAuthenticationProvider(options.ApiCredentials, options.NonceProvider))
{
    AddGenericHandler("Pong", (messageEvent) => { });
    SendPeriodic(TimeSpan.FromMinutes(1), con => new CoinExSocketRequest(NextId(), ServerSubject, PingAction));
}
````
With this as handler to prevent `unhandled message` logs:
````C#
/// <inheritdoc />
protected override bool MessageMatchesHandler(JToken message, string identifier)
{
    if (message.Type != JTokenType.Object)
        return false;
    return identifier == "Pong" && message["result"]?.ToString() == "pong";
}
````

**Comment by burakoner** [comment]
```C#
// https://github.com/JKorf/CryptoExchange.Net/blob/e8ee4e5ebc05f78bc7ff0a4605d32f337f8c9a27/CryptoExchange.Net/SocketClient.cs
foreach (var socket in sockets.Values)
```

This is exactly what I need. Thank you very much
