### ISSUE TITLE
HandleSubscriptionResponse

### ISSUE THREAD

**Issue by codehunter13** [JKorf/CryptoExchange.Net#119]
Hi,
Im trying to provide an implementation for Bybit.
When subscribing to a socket i receive already a data update before the subcribtion response:

First Data:
`Socket 1 received data: {"topic":"candle.1.BTCUSDT","data":[{"start":1638733800,"end":1638733860,"period":"1","open":48685.5,"close":48680,"high":48739.5,"low":48680,"volume":"22.649","turnover":"1103392.6665","confirm":false,"cross_seq":8564605788,"timestamp":1638733851111701}],"timestamp_e6":1638733851111703}` 

than subcription response: 
| Socket 1 received data: {"success":true,"ret_msg":"","conn_id":"7aaa1059-aeb7-4ded-ae3f-4e66578b12a4","request":{"op":"subscribe","args":["candle.1.BTCUSDT"]}}

than back data responses...

so i get the first data update in  HandleSubscriptionResponse. I thought i can return false (= no subscription response) and leave callresult null in HandleSubscriptionResponse. But this ends the socket connection.   
i think the returned false values is not used . it just checks the callresult?

`await socketConnection.SendAndWaitAsync(request, ResponseTimeout, data => HandleSubscriptionResponse(socketConnection, subscription, request, data, out callResult)).ConfigureAwait(false);`

Doesnt this have to check the return value and only close the connection WHEN RETURNING TRUE and callresult is not succeedded

The strange thing is it only goes wrong when setting breakpoint.s So when not debugging it seems he processes the subscription response first

**Comment by JKorf** [comment]
Hi, I'm working on a Bybit implementation myself currently. I hope you haven't spend too much time on it =/ 
It should be released in the coming weeks as part of a large update to all libraries.

On topic; I noticed as well that the data comes in before the actual subscription response which is a bit weird. The reason why it's not working with breakpoints is because there is a timeout on subscription responses and it probably expires before the messages is processed because its waiting on breakpoints.

**Comment by codehunter13** [comment]
Ok thx for letting me know. 
Is there a dev brach i can already use?

**Comment by JKorf** [comment]
Not yet, it's still private atm, but it will be available soon, as well as an alpha nuget package. Be aware that it is part of quite a big update to the CyrpoExchange.Net implementions, so you'll also have to do some work on the other implementations as method/property/namespaces have changed

**Comment by codehunter13** [comment]
ok. thx for the answers and all the hard work
