### ISSUE TITLE
NullReferenceException in SocketClient

### ISSUE THREAD

**Issue by mclean25** [JKorf/CryptoExchange.Net#12]
Hi @JKorf,

I'm getting the following error (using screenshot since I can't copy/paste in this case): 

![image](https://user-images.githubusercontent.com/7105182/54000338-d7066400-40fb-11e9-861a-1c9699b0c04e.png)

I'm using Binance.Net 4.09 & Bittrex.Net 3.0.7

**Comment by JKorf** [comment]
Hi, thanks for the report. This happened when there's an exception in the data handler for the socket and the exception handler for the socket isn't set:
````C#
var subResult = socketClient.SubscribeToAllSymbolTicker(data => { 
    // Exception thrown here
 });
subResult.Data.Exception // <- not set
````
I've fixed this, will be in the next nuget.

**Comment by JKorf** [comment]
New version has been pushed, along with a new version of Binance.net
