### ISSUE TITLE
Multiple exchange abstraction 

### ISSUE THREAD

**Issue by codehunter13** [JKorf/CryptoExchange.Net#120]
Hi,

To use multiple exchanges in an application we can use the common interface IExchangeClient for the rest client.
i dont think there is a common interface for the socket clients? or do i miss something?

The common interface IExchangeClient  for rest clients only works for 1 subclient ( mostly spot). It would be nice to get also an abstraction for this.
Something like IEXchangeClient.GetKlinesAsync(Subclient.SPOT,... 

Regards,
Glenn

**Comment by JKorf** [comment]
Hi, you're right, this is only for the rest client at the moment. 
I'm currently working on an update which has a more clear split in spot/futures endpoints which will allow me to have a IExchangeClient for the Spot endpoints and a similar interface for futures. The Spot and Futures endpoints don't always have the same implementation, so I'll probably have to create an IExchangeClient interface for the Futures api's which is similar to the IExchangeClient interface, maybe with some base methods.
It's in the pipeline.

**Comment by codehunter13** [comment]
Great!
