### ISSUE TITLE
Include a IRequestFactory in  RestClientOptions

### ISSUE THREAD

**Issue by EricGarnier** [JKorf/CryptoExchange.Net#121]
Hi @JKorf ,
the same way we can override the HttpClient in RestClientOptions, it would be nice to be able to provide our own IRequestFactory implementation directly in RestClientOptions, and not after creating the client.
I could provide a PR if you are interested.

Eric

**Comment by JKorf** [comment]
Hi Eric, I could add it in the next version. Are you using it for testing?

**Comment by EricGarnier** [comment]
@JKorf , no I don't code tests. And also, I found a other way to resolve my issue. So I don't really need this anymore. However it seem nice to have.

Eric

**Comment by JKorf** [comment]
I'm curious what you are using it for if you don't mind. Maybe it is something I can accommodate more easily in the libs.

**Comment by EricGarnier** [comment]
@JKorf , I was just trying to use http2 or http3.
So providing my own httpclient is enough for this.
