### ISSUE TITLE
arbitroge

### ISSUE THREAD

**Issue by mehdijalili2000** [JKorf/CryptoExchange.Net#122]
Hi. I want to use your project in multi exchange for Arbitroge bot 
that find best bid in first exchange and buy and withdraw and end sell in best ask exchange 
my question you ; Can this method be used due to network transmission delays or other issues? 
and Or what is the best way to do this? thank you

**Comment by mehdijalili2000** [comment]
Which exchange offices do you suggest? 

I have an error in using the transfer in  Coinex Exchange, which I mentioned in its section and you did not answer

**Comment by Mikes111** [comment]
Think that is not an issue. Please try the example and and find out which exchange is fine for you
