### ISSUE TITLE
info of OrderStatus

### ISSUE THREAD

**Issue by heavymanto** [JKorf/CryptoExchange.Net#124]
the OrderStatus states are Active, Filled, Canceled. In my business logic I would like to cancel orders that are not yet filled at a given moment. I would like to have the execution percentage or filledQuantity to calculate volume of opposite operation order.
![image](https://user-images.githubusercontent.com/6449169/151697357-eba10d02-de42-4e8a-b14e-15af7a8885a5.png)

Thanks

**Comment by JKorf** [comment]
This should be fairly easy to implement yourself with the data available isn't it?

**Comment by heavymanto** [comment]
Yes, with new version > 5.x there is QuantityFilled info. It's spread Quantity / QuantityFilled.

Thank's for your great work.

![image](https://user-images.githubusercontent.com/6449169/157730511-051689e2-1793-4b62-9293-668254602e2a.png)
