### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by mehdijalili2000** [JKorf/CryptoExchange.Net#127]
Is it possible to implement all exchange offices with this? And how ?

**Comment by mehdijalili2000** [comment]
You can give me a way of communication, you will not answer the email

**Comment by JKorf** [comment]
Each API has its own rules for withdrawing and its own symbol notation, this is something you'll have to consider. 

As I said, if you want to implement an other exchange with the CryptoExchange.Net library you'll have to look at another implementation as example. If you have some specific questions while implementing I'll be happy to answer them, but I don't have time to explain the whole process and structure at the moment.

Again, if you have any specific technical question feel free to open a new issue.
