### ISSUE TITLE
Option.Copy is difficult to use

### ISSUE THREAD

**Issue by EricGarnier** [JKorf/CryptoExchange.Net#128]
Hi @JKorf,
I just discover the new-cc, and I realize it is lot of work.
Thanks for that.
I still have a small question :

Concerning in BaseOption the Copy method
```
        public void Copy<T>(T input, T def) where T : BaseOptions
        {
            input.LogLevel = def.LogLevel;
            input.LogWriters = def.LogWriters.ToList();
            input.OutputOriginalData = def.OutputOriginalData;
        }

```

Wouldn't it be simple to have something like:
```
        public T Copy<T>() where T : BaseOptions, new()
        {
            T input = new T();
            input.LogLevel = this.LogLevel;
            input.LogWriters = this.LogWriters.ToList();
            input.OutputOriginalData = this.OutputOriginalData;
            return input;
        }

```
And in each derived class, something like:
```
        public new T Copy<T>() where T : BaseClientOptions, new()
        {
            var input = base.Copy<T>();

            input.Proxy = this.Proxy;
            input.ApiCredentials = this.ApiCredentials?.Copy();
            return input;
        }
```

Thanks again, and have a great day.

Eric

**Comment by JKorf** [comment]
Hi Eric, thanks for your input. I'm not sure this would work. How would this work when you have a status DefaultOptions object and you want to create a new options object based on those options, but override some of them? Say:
````csharp
BinanceClientOptions.SetDefaultOptions(new BinanceClientOptions{
  LogLevel = LogLevel.Trace,
  OutputOriginalData = true
});

var client = new BinanceClient(new BinanceClientOptions{
  OutputOriginalData = false
});
````

What I want this to do is have the client have options `LogLevel = Trace` and `OutputOriginalData = false`. Maybe I'm overlooking it, but I don't think you can easily do this when using your proposal can you?

Either way, thanks again for you input, I do agree that your implementation is cleaner.

**Comment by EricGarnier** [comment]
Hi @JKorf 
You are right, my proposal would not work as you like.
But for your case, I have an other proposition:
Create two construtors, like this, and remove the Copy method:
```
        public BaseOptions() : this(null)
        {
        }

        public BaseOptions(BaseOptions? baseOptions)
        {
            if (baseOptions != null)
            {
                this.LogLevel = baseOptions.LogLevel;
                this.LogWriters = baseOptions.LogWriters.ToList();
                this.OutputOriginalData = baseOptions.OutputOriginalData;
            }
        }

```
And 
```
        public BaseClientOptions() : this(null)
        {
        }

        public BaseClientOptions(BaseClientOptions? baseClientOptions) : base(baseClientOptions)
        {
            if (baseClientOptions != null)
            {
                this.Proxy = baseClientOptions.Proxy;
                this.ApiCredentials = baseClientOptions.ApiCredentials?.Copy();
            }
        }


```

And in Binance:
```
        public BinanceClientOptions() : this(Default)
        {
        }
        public BinanceClientOptions(BinanceClientOptions? binanceClientOptions) : base(binanceClientOptions)
        {
            if (binanceClientOptions != null)
            {
                this.ReceiveWindow = binanceClientOptions.ReceiveWindow;
                this.SpotApiOptions = new BinanceApiClientOptions(binanceClientOptions.SpotApiOptions);
                this.UsdFuturesApiOptions = new BinanceApiClientOptions(binanceClientOptions.UsdFuturesApiOptions);
                this.CoinFuturesApiOptions = new BinanceApiClientOptions(binanceClientOptions.CoinFuturesApiOptions);
            }
        }

```

What do you think of this? For the next CC ;-)

**Comment by JKorf** [comment]
I've refactored the options, mostly as you suggested. It should be more clear how it works now, have a look.

**Comment by EricGarnier** [comment]
Great, however, why is the second constructor in BinanceClientOptions internal?
I would like to use it to have a copy of my default choice. Typically, I have one BinanceClientOption with my default, and for some method, I use a second BinanceClientOption with more debug information.

**Comment by JKorf** [comment]
You could use it like this right?
````csharp
BinanceClient.SetDefaultOptions(new BinanceClientOptions
{
    ApiCredentials = new ApiCredentials("123", "456"),
    LogLevel = LogLevel.Warning,
    ReceiveWindow = TimeSpan.FromSeconds(10),
});

// Default options
var client1 = new BinanceClient();
// Default options but with Trace logging
var client2 = new BinanceClient(new BinanceClientOptions()
{
    LogLevel = LogLevel.Trace
});
````

**Comment by EricGarnier** [comment]
Yes.
But my code actually make no use of Default. I prefer to have no sharing via static property as Default.
So with the previous version of copy, my code is as follow:

    internal class MarketPlaceHuobi
    {
        private readonly HuobiClientOptions _huobiOption;

        private HuobiClientOptions HuobiOption { get { HuobiClientOptions r = new HuobiClientOptions(); _huobiOption.Copy(r, _huobiOption); return r; } }
        public MarketPlaceHuobi(Account account, BaseOptions options) : base(account, options)
        {
            _huobiOption = new HuobiClientOptions()
            {
                ApiCredentials = new CryptoExchange.Net.Authentication.ApiCredentials(account.ApiKey, account.ApiSecret),
                LogLevel = options.LogLevel,
                LogWriters = options.LogWriters.ToList(),
            };

Why do you prefer to have the second constructor internal ?

Eric

De : Jan Korf ***@***.***>
Envoyé : Thursday, February 24, 2022 4:20 PM
À : JKorf/CryptoExchange.Net ***@***.***>
Cc : EricGarnier ***@***.***>; Author ***@***.***>
Objet : Re: [JKorf/CryptoExchange.Net] Option.Copy is difficult to use (Issue #128)


You could use it like this right?

BinanceClient.SetDefaultOptions(new BinanceClientOptions

{

    ApiCredentials = new ApiCredentials("123", "456"),

    LogLevel = LogLevel.Warning,

    ReceiveWindow = TimeSpan.FromSeconds(10),

});



// Default options

var client1 = new BinanceClient();

// Default options but with Trace logging

var client2 = new BinanceClient(new BinanceClientOptions()

{

    LogLevel = LogLevel.Trace

});

-
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJKorf%2FCryptoExchange.Net%2Fissues%2F128%23issuecomment-1049966542&data=04%7C01%7C%7C88f432ad2f3b46b6568a08d9f7a91923%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637813127900639026%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=tB1C8f23fIWAO0AuR4jZbXrAQgcnWuNUN6dFOzq98yg%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFLW7FIXDJTIYPJWBOPARHTU4ZEBJANCNFSM5O4UUGJA&data=04%7C01%7C%7C88f432ad2f3b46b6568a08d9f7a91923%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637813127900639026%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=v8%2BzsRJwmKqzLGNhmbI2DHnQNDmouU46vk8G3MVXLcE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C88f432ad2f3b46b6568a08d9f7a91923%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637813127900639026%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=C%2Flq9JeSiQcnU5k0Mp%2BGmmPygWZqaczPBs7wAUIrm44%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C88f432ad2f3b46b6568a08d9f7a91923%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637813127900639026%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=11556ue%2FenBbINWL8iuGW6Y9IayNMH%2B1nvEUWoSmb%2F8%3D&reserved=0>.

**Comment by JKorf** [comment]
I try to keep the interfaces clean, without too much overloads which people generally don't use. Since the `copy` constructor is only there for internal use for Default options, or at least that's what I initially implemented it for, I don't want to expose it.

**Comment by EricGarnier** [comment]
Ok, I can understand.
Thanks for the explanation.

Eric
