### ISSUE TITLE
Improve socket client architecture

### ISSUE THREAD

**Issue by JKorf** [JKorf/CryptoExchange.Net#129]
See https://github.com/JKorf/Bittrex.Net/issues/208

**Comment by heavymanto** [comment]
about that it would be really nice if there were some common methods on interface, for example SubscribeToBookTickerUpdatesAsync

**Comment by JKorf** [comment]
Closing as websocket architecture has been adjusted and I'm happy with the state it's currently in.
Common methods are also available now.
