### ISSUE TITLE
Rate Limiters for API Keys

### ISSUE THREAD

**Issue by burakoner** [JKorf/CryptoExchange.Net#13]
Hi @JKorf ,

Is is possible to add an extra rate limiter option for Api Key? It's more important than Total or EndPoint in Huobi.

Have a nice day

**Comment by JKorf** [comment]
Hi Burak,
What would expect of this? An API key is bound to a client, so if you set a TotalRateLimit for the client you are restricting the calls per API key right? If you're using it in a different way please let me know how.

**Comment by burakoner** [comment]
From Binance habits, I use only one Binance.Net or Huobi.Net Object in all software, So I can manage rate limiters. Before I send a request I change Api Key and Secret of Object every time. So TotalRateLimit does not satisfy needs

**Comment by JKorf** [comment]
Ah I see. I've just released an update for all libs which include CryptoExchange.Net and added a `RateLimiterAPIKey` which will limit the requests per API key.

**Comment by burakoner** [comment]
Thank you @JKorf . Long live @JKorf  :)
