### ISSUE TITLE
Version confliction

### ISSUE THREAD

**Issue by Tendx** [JKorf/CryptoExchange.Net#130]
Hi JKork,
I appreciate all the related library, they are really useful. Awasome~

I met a version confiction after it updated:
I have an project which refer to Binance.Net, Huobi.Net and Okex.Net.
B and H used CryptoExchange.Net v5.1.2, and O used v4.2.8.
When building, I would get an error:
**Error CS7069 Reference to type 'RestClient' claims it is defined in 'CryptoExchange.Net', but it could not be found**
Then I realized CryptoExchange.Net has made some breaking change.

I don't know how to use CryptoExchange.Net with two version, and I just used source code (Okex.Net and CryptoExchange.Net) to work around it.
Do you have any ideas?

**Comment by JKorf** [comment]
Unfortunately it isn't possible to have different versions of the same dll in a dotnet project, which causes the issue you're having.
This is an issue for which I haven't found a good solution yet. For the libraries I manage myself it's not much of a problem as I can just update them myself with the latest CryptoExchange.Net release when it comes out, but 3rd party implementation will often not be on the latest version.

If you have any suggestions for how to handle this please share, but for now I'll see if I can get Okex.Net to update to the latest version.
