### ISSUE TITLE
Interface IBybitClientUsdPerpetualApiExchangeData throws error on every method

### ISSUE THREAD

**Issue by uppermosteN** [JKorf/CryptoExchange.Net#131]
I am trying to do a simple **GetKlinesAsync** with the **IBybitClientUsdPerpetualApiExchangeData** interface like this:

`var klineData = (await client.UsdPerpetualApi.ExchangeData.GetKlinesAsync("BTCUSDT", Bybit.Net.Enums.KlineInterval.OneMinute, DateTime.UtcNow.AddMinutes(-150), limit: 200)).Data;`

and I'm being thrown the following exception: 

`Method not found: 'System.Uri CryptoExchange.Net.ExtensionMethods.SetParameters(System.Uri, System.Collections.Generic.SortedDictionary``2<System.String,System.Object>)'.`

***

Further investigating, I'm finding out that none of the tested methods in **UsdPerpetualApi** interface are working; for example a simple 

`var symbolData = await client.UsdPerpetualApi.ExchangeData.GetSymbolsAsync();`

yields the same error as above while something similar from the **InversePerpetualApi** or even **Spot** is working correctly and successfully getting the data needed.

**this works:** 
` var symbolData = await client.InversePerpetualApi.ExchangeData.GetSymbolsAsync();`

***

I have opened this issue in the CryptoExchange.Net repo instead of the Bybit.Net one since that's the package where the error gets thrown.

I also have to specify that I am using Bybit.Net v0.0.4 & CryptoExchange.Net v5.1.4 packages which are latest at the time of my finding. Thanks for developing this wrapper for Bybit and I am looking forward for any information on this issue!

**Comment by JKorf** [comment]
Hi @uppermosteN, thanks for the detailed report. Can you try using the CryptoExchange.Net v5.1.3 package instead? That should work for you. Generally its a good idea to keep the CryptoExchange.Net version as the one that's referenced in the implementation. Bybit hasn't yet been updated for 5.1.4 yet, but should be shortly.

**Comment by uppermosteN** [comment]
Thanks a lot @JKorf ! 

The v5.1.3 package works great with the current version of Bybit.Net v0.0.4. I used to work with Binance.Net and when I started coding for Bybit, I got the CryptoExchange.Net package first and then the Bybit.Net package - that's why it was v5.1.4 and not the one referenced.
