### ISSUE TITLE
Allow Blank Successful Responses From API

### ISSUE THREAD

**Issue by Deon-v** [JKorf/CryptoExchange.Net#137]
**Describe the bug**
Add ```SendRequestAsync``` to ```BaseRestClient``` that allows for a request to be made that returns an empty response.
I also noticed in the logs below that it says Sending GET request but this is a DELETE Request

**To Reproduce**
I tried to get this to work by using ```SendRequestAsync<object>``` ```SendRequestAsync<string>``` but neither of these work.

**Expected behavior**
I would expect a response with a status code and no data, if the request does fail it would fall back to the error response.

**Debug logging**
2022/04/27 16:08:14:021 | Trace | Valr       | [2] Sending GET request to https://test.valr-api.com/
2022/04/27 16:08:14:029 | Debug | Valr       | [0] Response received in 0ms: 
2022/04/27 16:08:14:030 | Error | Valr       | Empty data object received
2022/04/27 16:08:14:032 | Error | Valr       | Empty data object received
2022/04/27 16:08:14:034 | Debug | Valr       | [1] Failed to sync time, aborting request: : Empty data object received

**Comment by JKorf** [comment]
Hi, I've added this in the latest version, you can now use `SendRequestAsync` without type parameter to receive an empty response
