### ISSUE TITLE
using clients as Singleton instance or Scoped?

### ISSUE THREAD

**Issue by hatami57** [JKorf/CryptoExchange.Net#138]
Hi,
I wanna make an exchange as a service to be used in dependency injection.
Should I use say BinanceClient as a singleton instance? I mean create an instance during all application lifetime, or is it better to create a new instance everytime we need to make a request to Binance? (scoped or transient dependency)

**Comment by JKorf** [comment]
Either is fine for rest clients. If you're deciding to go for `creating an instance per request` you should set an HttpClient instance in the default options for the rest client:
````
BinanceClient.SetDefaultOptions(new BinanceClientOptions{
  HttpClient = clientInstance
});
````
If no client is set it will create a new HttpClient each time, which is bad for business.

The socket client will close all connections when disposed, so you'd probably want to make that Singleton if you're using it.

**Comment by hatami57** [comment]
Thank you Jan for your detailed response🙏
So if I wanted to go for `creating an instance per request` and wanna use `IHttpClientFactory`, I can use it as follows:

```
BinanceClient.SetDefaultOptions(new BinanceClientOptions{
  HttpClient = httpClientFactory.CreateClient()
});
```

Is it okay?
🌹🙏

**Comment by JKorf** [comment]
Yep, thats fine!

**Comment by hatami57** [comment]
Thanks🙏🌹
