### ISSUE TITLE
Subscribe without any news

### ISSUE THREAD

**Issue by xiuxiang** [JKorf/CryptoExchange.Net#139]
> Available commands: PlaceOrder, GetBalances, GetOpenOrders, CancelOrder, GetPrice, SubscribePrice
SubscribePrice
> Exchange?
BTCUSDT
> Symbol?
BTCUSDT
Subscribing price...

Other interface tests output results normally

visual studio 8.10.14
examples--->ConsoleClient

**Comment by JKorf** [comment]
You entered BTCUSDT as Exchange, try Binance
