### ISSUE TITLE
[Feature Requsest] Bitstamp Wrapper

### ISSUE THREAD

**Issue by gensleralexander** [JKorf/CryptoExchange.Net#14]
Hello,
thank you for your amazing work on the API wrappers.
I know it's a bit different from exchanges like Binance etc., but do you have any plans on doing a wrapper for the Bitstamp API?
https://www.bitstamp.net/api/

Greetings
Alexander

**Comment by JKorf** [comment]
Hi, I've added a list of planned exchanges on the readme, I've added Bitstamp on that. Note that I can't give a planning on when I might get to it.

**Comment by gensleralexander** [comment]
Thank you for adding it to the list.
