### ISSUE TITLE
Disposed Order Books are trying to reconnect on Socket timeout

### ISSUE THREAD

**Issue by nathan-datusarator** [JKorf/CryptoExchange.Net#140]
**Describe the bug**
Server is jumping to 100% CPU.  At the time this happens the following log is produced

> 2022/05/12 00:01:00:212 | Warning | Binance    | Socket 5 error: Websocket error code ConnectionClosedPrematurely, details: WebSocketException - The remote party closed the WebSocket connection without completing the close handshake.
>    at System.Net.WebSockets.WebSocketBase.WebSocketOperation.<Process>d19.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Net.WebSockets.WebSocketBase.<ReceiveAsyncCore>d45.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.<ReceiveLoopAsync>d__85.MoveNext()
> 2022/05/12 00:01:00:244 | Warning | Binance    | Socket 5 Connection lost, will try to reconnect
> 2022/05/12 00:01:00:244 | Warning | Binance    | Binance order book BTCUSD connection lost
> 2022/05/12 00:01:00:244 | Information | Binance    | Binance order book BTCUSD status changed: Disposed => Reconnecting
> 2022/05/12 00:01:00:244 | Warning | Binance    | Binance order book BTCUSD connection lost
> 2022/05/12 00:01:00:244 | Information | Binance    | Binance order book BTCUSD status changed: Disposed => Reconnecting
> 2022/05/12 00:01:00:244 | Warning | Binance    | Binance order book ETHUSD connection lost

+ a dozen more since I will keep track of which order books are being accessed and dispose them using the following code

> try {
>     await Book.StopAsync();
>   } catch (Exception ex) {
>     GeneralUtils.LogError<OrderBookHandler>("Stop", ex);
>   } finally {
>     Book.Dispose();
>     Book = null;
>   }

**To Reproduce**
I've tried to manually reproduce this on my machine by turning off internet and other socket failures.  It also happens so rarely that Debug logging isn't practical at this time.  I will look through the code and maybe add notes if I see something that is helpful

**Expected behavior**
Disposed notebooks are not being Garbage Collected.  Not sure if its on my side but need to be sure on CEN side.  Regardless, the reconnect loop should ignore any books in Disposed status

**Comment by nathan-datusarator** [comment]
Normal Cycle is followed (3 min timeout)

```
2022/05/12 03:37:45:165 | Information | Binance    | Binance order book BTCUSD status changed: Connecting => Syncing
2022/05/12 03:37:45:617 | Information | Binance    | Binance order book BTCUSD status changed: Syncing => Synced
2022/05/12 03:40:45:645 | Information | Binance    | Binance order book BTCUSD status changed: Synced => Disconnected
2022/05/12 03:40:45:754 | Information | Binance    | Binance order book BTCUSD status changed: Disconnected => Disposing
2022/05/12 03:40:45:754 | Information | Binance    | Binance order book BTCUSD status changed: Disposing => Disposed
```

**Comment by nathan-datusarator** [comment]
My best guess is I'm going from Disconnected to Disposed too quickly for the ProcessQueue loop (on line 802 of SymbolOrderBook.cs) to notice and thus it doesn't actually drop out.  Any reason not to patch with a check of both Disconnected and Disposed?

Also add a safety check at line 577 in Reset for Status == OrderBookStatus.Disposed

Finally, the lambda expressions on _subscription are nice, but aren't they causing soft hooks to remain on the SymbolOrderBook and thus never letting the object be actually GCed?  I'm trying to see if that _subscription object is shared when a shared socket is used and it appears to be so would need to have the events use explicit functions with += and -=

**Comment by JKorf** [comment]
I think you're right. Your PR has been merged and is active in the latest library versions. Let me know if you ever see it again
