### ISSUE TITLE
Proxy information is cleared when reconnecting

### ISSUE THREAD

**Issue by wurucu** [JKorf/CryptoExchange.Net#145]
### The Issue :
When the connection established using the proxy is disconnected, the new connection is not established with the proxy.
 
### Related code :
```
Sockets/SocketConnection.cs > ReconnectAsync

> _socket.Reset();

CryptoExchangeWebSocketClient.cs > Reset

> _socket = CreateSocket();
```

### Estimated solution:
Proxy information assigned with SetProxy is stored in the local variable. After the new socket is created with CreateSocket, the proxy information in the local variable is reassigned.

**Comment by JKorf** [comment]
Has been fixed
