### ISSUE TITLE
WebSocket: unable to handle malformed websocket data

### ISSUE THREAD

**Issue by michielpost** [JKorf/CryptoExchange.Net#146]
**Describe the bug**
I'm trying to work with websocket data from bkex.com. I'm unable to handle their websocket response data with CryptoExchange.Net.

This is data that I am receiving:
```
42/quotation,["quotationOrderDepth",{"symbol":"BTC_USDT","ts":1654459536986,"asks":[["30094.52","1.16111"],["30096.94","0.51836"]],"bids":[["30094.20","1.48850"],["30093.98","0.89371"]]}]
```

It is being converted to a JToken, but fails and returns null:
https://github.com/JKorf/CryptoExchange.Net/blob/master/CryptoExchange.Net/Sockets/SocketConnection.cs#L449

It then goes into the backup flow, I assume to return it as a simple string.
https://github.com/JKorf/CryptoExchange.Net/blob/master/CryptoExchange.Net/Sockets/SocketConnection.cs#L450-L456
```
"42/quotation,["quotationOrderDepth",{"symbol":"BTC_USDT","ts":1654459536986,"asks":[["30094.52","1.16111"],["30096.94","0.51836"]],"bids":[["30094.20","1.48850"],["30093.98","0.89371"]]}]"
```
Tries to create a JToken of that:
tokenData = data.ToJToken(log);

That also fails with this error:
`: 'Additional text encountered after finished reading JSON content: q. Path '', line 1, position 16.'`

So the result is null and I'm unable to handle this message.

Any workaround for this? Or is it a bug that can be solved?

**Comment by JKorf** [comment]
I'd suggest to use the `SetDataInterpreter` method to set a string interpreter method which transforms the data into valid json which can then best processed
