### ISSUE TITLE
Time is Synced at the wrong time

### ISSUE THREAD

**Issue by HypsyNZ** [JKorf/CryptoExchange.Net#147]
**Describe the bug**
When TimeSync is checked it is checked before the request

**To Reproduce**
Make a request

**Expected behavior**
Time is Synced after the request as it should already be in sync and this is just for adjustments.

**Debug logging**
Not required

**Discussion**

**Comment by JKorf** [comment]
Has been changed a little while back; the first time it is checked and awaited before the request, every time after that it is checked on the background
