### ISSUE TITLE
Dependency injection support

### ISSUE THREAD

**Issue by Kimiguro** [JKorf/CryptoExchange.Net#15]
Hi! Awesome library! Maybe create Abstractions project with all interfaces to easy register in IOC?

**Comment by Kimiguro** [comment]
Will not need to connect the full library where you need to work only with interfaces

**Comment by JKorf** [comment]
Hi, sorry for the delayed response, was on holiday.

Can you explain why you would just want the interface? Wouldn't you still need the whole library for it to actually 'work'?

**Comment by Kimiguro** [comment]
Hi! I just saw your answer. Of course I need the whole library. Separating the interface from the implementation will allow you to use abstractions separately from the library. That is, in a multi-layer architecture, I can place the library at the service level, and use interfaces at the application level without having to connect the whole library.
This is not a request, but rather a proposal for improvement

**Comment by JKorf** [comment]
Hi, I can see the advantages of having them separated, however that would mean either I have to make interfaces for all model objects, which is a lot of work to make and maintain, or all the objects have to be in the interface project which I don't like..
