### ISSUE TITLE
Feature request - DataEvent constructor

### ISSUE THREAD

**Issue by walterX12** [JKorf/CryptoExchange.Net#150]
I am writing Binance simulator based on Binance.Net. I have recently migrated from 6.x to 8.x version. In new version I need to "override" methods returning `CryptoExchange.Net.Sockets.DataEvent` . Due to the fact that `CryptoExchange.Net.Sockets.DataEvent` does not have public constructor I am stuck in upgrade process, because I am not able to construct "fake/simulator" DataEvent

Is there a chance to make constructor `DataEvent(T data, DateTime timestamp)` public ?

Regards

Petr

**Comment by JKorf** [comment]
Hi, I've added a public constructor for DataEvent in the latest version
