### ISSUE TITLE
EnumConverter writes strings without quotes

### ISSUE THREAD

**Issue by andreyea** [JKorf/CryptoExchange.Net#151]
**Describe the bug**
When I serialize an object with enum property, EnumConverter writes json without quotes. For example {"Type":Spot}

**To Reproduce**
Create an object of class BinanceSpotAccountSnapshot, which contains Type property and [JsonConverter(typeof(EnumConverter))] attribute. Serialize the object using Newtonsoft. The result string will contain property Type value without quotes like so: {"Type":Spot}. If you try to deserialize the string, the operation will fail. 

**Debug logging**
ex = {"Unexpected character encountered while parsing value: S. Path 'Type', line 1, position 35."}

**Comment by JKorf** [comment]
Thanks for the report, has been fixed in the latest version
