### ISSUE TITLE
Format conversion error

### ISSUE THREAD

**Issue by wecando168** [JKorf/CryptoExchange.Net#155]
https://github.com/JKorf/CryptoExchange.Net/blob/417cf2f9ac05e6ca6ac57364c4601f25d7a62782/CryptoExchange.Net/Converters/ArrayConverter.cs#L109
For the received data, if the decimal format is "2.345E-4", the method will report an error, replace "value..Contains("e") " to "value.ToString().IndexOf("e",StringComparison.OrdinalIgnoreCase) >= 0)", can process the input of the following two formats at the same time ("2.345E-4" or "2.345e-4"), no error is reported

**Comment by JKorf** [comment]
Has been fixed
