### ISSUE TITLE
Info - CalculateAverageFillPrice by asset quote

### ISSUE THREAD

**Issue by heavymanto** [JKorf/CryptoExchange.Net#170]
I would like to congratulate you again on the great and fascinating work you have done. Your library is a source of many inspirations, the architecture you set up is excellent.

I have a financial trade buddy and would like your opinion. To calculate the average price of a volume, the library already provides the CalculateAverageFillPrice method, which, starting from a volume in asset base, returns the AVG volume based on the order book. In some cases, however, it would be useful for me to have the average price starting from the volume of the asset quote instead of the base.

Example I have 1000USDT on the BTC/USDT asset and would like to know how many BTC I could buy. Generally the price of the symbol ticker is used for all the volume but is it a precise change? Is there a financial algorithm that returns the asset base price from the asset quote based on the order book?

Thank you

**Comment by JKorf** [comment]
This has been added, I've added a function `CalculateTradableAmount` on the order book
