### ISSUE TITLE
unsafe access to subscriptions collection on SocketConnection.ProcessReconnectAsync

### ISSUE THREAD

**Issue by sagi519** [JKorf/CryptoExchange.Net#172]
**Describe the bug**
There is an unsafe access to subscriptions collection on SocketConnection.ProcessReconnectAsync. line 632 which sometime throws InvalidOperationException with "collection was modified" message (or something like that)

**To Reproduce**
using many subscriptions will probably reproduce the issue

**Expected behavior**
The existing subscriptions lock should be used. The fix is very simple.

**Comment by JKorf** [comment]
Has been fixed
