### ISSUE TITLE
Can not connect with credentials: Kraken SetDefaultOptions not available

### ISSUE THREAD

**Issue by cr0wburn** [JKorf/CryptoExchange.Net#18]
Following your example at CryptoExchange.Net the following code does not work:

```
using Kraken.Net;
using CryptoExchange.Net;
using CryptoExchange.Net.Authentication;

KrakenClient.SetDefaultOptions(new KrakenClientOptions
	{
		ApiCredentials = new ApiCredentials("apiKey", "apiSecret")
	});

```
SetDefaultOptions is not available or missing.

Thanks for this nice API wrapper, love your work thus far.

![api_key_default](https://user-images.githubusercontent.com/6381581/64603089-2174e000-d3c0-11e9-93c3-1b3b1aa548f3.png)

**Comment by JKorf** [comment]
Hi, you're right, forgot to add those in. I've pushed version 0.0.2 which should be available in a few minutes.
Let me know if you have any other issues!

**Comment by cr0wburn** [comment]
Thank you!
I will try and connect to kraken and do stuff, so if i find any problems, i'll report :)

As a workaround i used the code:
```

KrakenClientOptions options = new KrakenClientOptions();
            options.ApiCredentials = new ApiCredentials(krakenKey, krakenSecret);
            var client = new KrakenClient(options);

```
Thanks for the fix!
