### ISSUE TITLE
Mexc wrapper?

### ISSUE THREAD

**Issue by HamidZaeri** [JKorf/CryptoExchange.Net#184]
Hi @JKorf 
Is there any plan for a wrapper to mexc exchange api?
https://www.mexc.com/mexc-api

And what is your relation with below package? It has links to your GitHub!
https://www.nuget.org/packages/Mexc.Net

**Comment by JKorf** [comment]
Hi, I have not decided on the next exchange to implement, and also I'm not sure when I'll be able to work on the next one. But I'll keep your recommendation in mind. 

The package has nothing to do with me, it's just a 3rd party developer who made it based on my CryptoExchange.Net base package, which they're free to do. Use it with caution, I don't know anything about it.
