### ISSUE TITLE
Kraken StartAsync() method not async

### ISSUE THREAD

**Issue by cr0wburn** [JKorf/CryptoExchange.Net#19]
When i try to use:

var startResult = await orderBook.StartAsync();

i get an error: "CS4033	The 'await' operator can only be used within an async method. Consider marking this method with the 'async' modifier and changing its return type to 'Task'.	"

It seems that the KrakenSymbolOrderBook.StartAsync() method is not async.

**Comment by JKorf** [comment]
It should be async as far as I can see. Make sure the method you're calling it from is also marked async.

**Comment by cr0wburn** [comment]
I'm an idiot, i forgot to make the calling method async (my own method).

**Comment by JKorf** [comment]
Been there, done that ;)
