### ISSUE TITLE
KrakenOrderbookOptions error messages

### ISSUE THREAD

**Issue by cr0wburn** [JKorf/CryptoExchange.Net#20]
Code (this is basicly from the examples):
`KrakenSymbolOrderBook orderBook = new KrakenSymbolOrderBook("XXBTZEUR", 1, new KrakenOrderBookOptions(20));`

Gives an error message:
CS1503	Argument 1: cannot convert from 'int' to 'Kraken.Net.Interfaces.IKrakenSocketClient'

When i change it like this:
```
var client = new KrakenSocketClient(options);
KrakenSymbolOrderBook orderBook = new KrakenSymbolOrderBook("XXBTZEUR", 1, new KrakenOrderBookOptions(client));

```
The error is gone But now when connecting using the following:
```
 var startResult = await orderBook.StartAsync();

            if (!startResult.Success)
            {
                Console.WriteLine("Error starting order book synchronization: " + startResult.Error);
               return;
            }

```
It stops, because startResult.Error is:
{3: Server error: Subscription depth not supported}

Which makes sense because a client is not a depth :)
Is this an issue, or a user error ?

**Comment by cr0wburn** [comment]
By changing the KrakenSymbolOrderBook to:
KrakenSymbolOrderBook orderBook = new KrakenSymbolOrderBook("XBT/EUR", 100);

It works like a charm, thank you for your help.

**Comment by cr0wburn** [comment]
I have never worked with WebSockets before, and you are super helpfull. :)

 var subResult = client.SubscribeToTickerUpdates("XBT/EUR", data => { });
subResult contains Succes = true;

But where does the Kraken.Net.Objects.KrakenStreamTick go ?
I don't know how to get it, and after i get it, how do i get an updated value at the next tick ?
Sorry for posting a non issue, but maybe this can be added to the manual.

Thanks(and sorry)

**Comment by JKorf** [comment]
The websocket connection works based on events. So when you're calling `SubscribeToTickerUpdates` you connect to a stream and when data is received on that stream you get an update. To handle the update you'll have to pass an update handler to the subscribe method. This is what the `data => {}` bit is. 
Between the {} you'll have to handle the data. What to do with it is obviously up to you, but having a console application this will simply write the price of the latest tick to the console:
````C#
client.SubscribeToTickerUpdates("XBT/EUR", data => { 
      Console.WriteLine(data.Market + " last trade price: " + data.Data.LastTrade.Price);
});
````

**Comment by cr0wburn** [comment]
Thank you, this is exactly what i needed to know!
I did it like this (as an example)

```
var subResult = client.SubscribeToTickerUpdates("XBT/EUR", data => Ticker(data));
 
      static void Ticker(Kraken.Net.Objects.Socket.KrakenSocketEvent<Kraken.Net.Objects.KrakenStreamTick> tick)
        {
            var a = tick.Data;
            var bid = a.BestBids;
            var ask = a.BestAsks;
        }
```

**Comment by JKorf** [comment]
Yup that's fine.
(You could shorthand it by writing `client.SubscribeToTickerUpdates("XBT/EUR", Ticker);`, which is the same)
