### ISSUE TITLE
Question: Does this library or CryptoClients.Net have built-in support for local orderbook management?

### ISSUE THREAD

**Issue by Svetomech** [JKorf/CryptoExchange.Net#206]
Hello!

I was interested, does your library keep a local snapshot of an orderbook and applies deltas to it based on exchanges rules (e.g. [Binance](https://developers.binance.com/docs/binance-spot-api-docs/web-socket-streams#how-to-manage-a-local-order-book-correctly), [Bybit](https://bybit-exchange.github.io/docs/v5/websocket/public/orderbook#process-snapshotdelta)), or do we need to handle this logic ourselves? I was curious, because I saw that functionality in ccxt library (e.g. [Bybit](https://github.com/ccxt/ccxt/blob/master/cs/ccxt/exchanges/pro/bybit.cs#L820)), but to my understanding your library only provides us with UpdateType (snapshot or delta), and we need to handle rest of the logic ourselves to keep orderbook in sync?

Thanks in advance.

**Comment by JKorf** [comment]
Hi, this `CryptoExchange.Net` library is a base library which is used by my client libraries. But the `CryptoClients.Net` package does indeed have this functionality.
See https://jkorf.github.io/CryptoExchange.Net/#idocs_orderbooks

**Comment by Svetomech** [comment]
Wow, cool, I somehow missed that. Thanks you very much!
