### ISSUE TITLE
Can't get options order books (Bybit)

### ISSUE THREAD

**Issue by heinsenberg82** [JKorf/CryptoExchange.Net#208]
I'm trying the following code:

```csharp
var book = orderBookFactory.Options.Create("ETH", "USDC");
        var startResult = await book.StartAsync();
        if (!startResult.Success)
        {
            // Handle error, error info available in startResult.Error
        }

        if (book.Status == OrderBookStatus.Syncing)
        {
            Console.WriteLine(book.BestBid.Price);
        }
        
        await book.StopAsync();
```

However, the `startResult` is unsuccessful and I'm getting the following sync error: `[ServerError] Timeout while waiting for data.`

I'm specifically trying the overload of the `Create` method that accepts `baseAsset` and `quoteAsset` as parameters, to check what exactly this method would return, as I couldn't find more details in the documentation.

**Comment by JKorf** [comment]
Options trading specifically don't really work with the order book, however you could make it work with a specific symbols, for example `orderBookFactory.Options.Create("BTC-14NOV24-74000-P");`
