### ISSUE TITLE
Logs on file

### ISSUE THREAD

**Issue by nikkozp** [JKorf/CryptoExchange.Net#21]
Hey.

How can I write logs (`log.Write(LogVerbosity.Debug, message);`) to a file?

**Comment by JKorf** [comment]
Hi, you can add TextWriters to the options like this:
````C#
            var writer = new StreamWriter(File.OpenWrite("path-to-ouput"));
            var client = new BinanceClient(new BinanceClientOptions()
            {
                LogWriters = new List<TextWriter> { writer },
                LogVerbosity = LogVerbosity.Debug
            });
````
Note that this only works for a single client, I'm pretty sure this isn't thread safe for multiple clients. Consider using a logging library if you need that.

**Comment by nikkozp** [comment]
Thanks a lot. Will test on several clients, if that the tickles will make PR
