### ISSUE TITLE
UpdateTime to be marked virtual

### ISSUE THREAD

**Issue by badokun** [JKorf/CryptoExchange.Net#217]
Can this property be marked as virtual? I'm implementing an exchange using CryptoExchange.Net, however I want that property to reflect the timestamp as reported in the payload published by the exchange. Currently it's using the DateTime.UtcNow, but I want to track latency from the exchange to my server.

I'm tracking the BestOffers, so when the event is raised I'd like to consider if the data is still relevant. If the latency is too great, one may assume it's no longer available.

https://github.com/JKorf/CryptoExchange.Net/blob/168dabc11fdca7243ea2e8d283c99480197815bf/CryptoExchange.Net/OrderBook/SymbolOrderBook.cs#L130

**Comment by JKorf** [comment]
Hi, I think you could also just add a new property in a derived class right?

**Comment by badokun** [comment]
Yes that's what I ended up doing, thanks.
