### ISSUE TITLE
add referral links

### ISSUE THREAD

**Issue by vslee** [JKorf/CryptoExchange.Net#220]
I see that in a couple of your exchanges, you included a referral link for ppl to sign up using. But some of the exchanges you don't have a link. I don't know if you have accounts at all exchanges, but it might be worth signing up. That way you could provide referral links for the remaining ones.

**Comment by JKorf** [comment]
Hi, thanks for the suggestion. Due to restrictions from the exchange which countries they serve (The Netherlands is often not supported due to regulations) I can't have personal accounts on all exchanges. Which is why there aren't referral links for all of them.

**Comment by vslee** [comment]
Makes sense. I also noticed you added some just now such as cryptocom.
