### ISSUE TITLE
KlineTracker snapshot is incorrect

### ISSUE THREAD

**Issue by amykhaylyshyn** [JKorf/CryptoExchange.Net#222]
KlineTracker is using Dictionary to store klines and it removes kline at index 0 assuming Dictionary is ordered using DateTime, however, it is wrong assumption:
https://stackoverflow.com/questions/4007782/the-order-of-elements-in-dictionary

As a result it always removes the most recent kline and snapshot is never updating.

![image](https://github.com/user-attachments/assets/acf3fee8-cb59-49e6-86a7-00fe98c68034)

**Comment by JKorf** [comment]
Ah you're right. I'll fix this. Easy change to SortedDictionary.
