### ISSUE TITLE
Questions About SharedApis WS Updates and HF Endpoints

### ISSUE THREAD

**Issue by masherak** [JKorf/CryptoExchange.Net#223]
First of all, thank you for your excellent work on unifying APIs across different exchanges. 

I have two questions regarding the current implementation:
	1.	WebSocket Update Intervals:
How do you handle WebSocket update timing? I couldn’t find any parameter that controls the update interval. Does it always default to the fastest interval available on each supported exchange?
	2.	Access to HF Endpoints:
Is it possible to access high-frequency (HF) endpoints through this unified interface? For example, on KuCoin, HF trading is managed via the IKucoinRestClientSpotApiHfTrading interface. Can this be accessed through SharedApis?

Thanks in advance for your response!

**Comment by JKorf** [comment]
Hi,

Thanks for your kind words.

1. Yes the fastest update time is currently selected by default.
2. By default Kucoin HFTrading enpoints will be used. This can be disabled by setting the `HfTrading` parameter to false (`ExchangeParameters.SetStaticParameter("Kucoin", "HfTrading", false);`) in which case the normal trading endpoints will be used.

**Comment by masherak** [comment]
Thank you very much
