### ISSUE TITLE
Managing local order book using SubscribeToDepthUpdatesAsync

### ISSUE THREAD

**Issue by BenDavison** [JKorf/CryptoExchange.Net#25]
Hi,
  Im trying to maintain a synchronized orderbook using the SocketClient provided in your API wrapper however there is no Nonce information in KrakenStreamOrderBook or KrakenOrderBook and no clear indication on how this might work without one.  I cannot find any documentation on the Kraken API FAQs etc that help.  Have you got this working and if so could you please provide a little information on the flow or point me at existing documentation that might help.

  Good work with the .Net wrappers I am already using your Binance and Bittrex offerings.  Once my application is up and running I will make a donation.

Many thanks

Ben

**Comment by JKorf** [comment]
Hi Ben,

After subscribing to the order book stream the first update you receive is a snapshot of the current state of the book. Every update after that is a change on the order book. So maintaining an order book is relatively straight forward; save the snapshot and update it with each following update.

As you mentioned, sadly they haven't implemented a nonce so we can't validate that we haven't missed a message. That's a limitation of their current API. 

Have you seen my `SymbolOrderBook` implementations? Each library has an implementation of a local order book. For Kraken for example that is `KrakenSymbolOrderBook`. These implementations automatically sync a local order book and handle stuff like reconnecting. You can also just check those implementations as a reference for your own implementations of course.

Let me know if you run into any issues.

**Comment by BenDavison** [comment]
Thanks for the info... very helpful.

I have tried to push a small change to a branch  from master that you might be interested in, with a view to opening a PR.  However Im getting github error

Pushing book_streams
Error encountered while pushing branch to the remote repository: Git failed with a fatal error.
unable to access 'https://github.com/JKorf/CryptoExchange.Net.git/': The requested URL returned error: 403
Pushing to https://github.com/JKorf/CryptoExchange.Net.git

do you encourage PRs from the community?  Im just wondering if this is my end or your repo is actively refusing my push.

Ben

**Comment by JKorf** [comment]
PR are welcome :)
You should be able to create a PR from a fork.

**Comment by BenDavison** [comment]
now using SymbolOrderBook
