### ISSUE TITLE
BaseSocket typo on remove event from OnOpen?

### ISSUE THREAD

**Issue by stran73** [JKorf/CryptoExchange.Net#3]
public event Action OnOpen
        {
            add => _openhandlers.Add(value);
            remove => _closehandlers.Remove(value);
        }
I suppose on remove it should be also _openhandlers

**Comment by JKorf** [comment]
Hi, yes it should, a typical copy/paste error. Thanks for the report, fixed in the next version.

**Comment by JKorf** [comment]
Fixed in the latest version of all clients.
