### ISSUE TITLE
Exceptions thrown in SymbolOrderBook flow

### ISSUE THREAD

**Issue by BenDavison** [JKorf/CryptoExchange.Net#30]
Hi,

  I have been using SymbolOrderBook cache to maintain a local order book but Im getting exceptions like the one below...  

**2020/02/10 10:01:12:320 | Info | Socket 133 error: Microsoft.AspNet.SignalR.Client.Infrastructure.SlowCallbackException: Possible deadlock detected. A callback registered with "HubProxy.On" or "Connection.Received" has been executing for at least 10 seconds.**

- To reproduce this easily Im connecting to 60pairs all with their own "new BittrexSymbolOrderBook(exchangeSymbol)" even once all pairs are synced these exceptions happen on a regular basis and cause resynchronization.  Note Im also seeing this for other exchanges but it appears more frequently on the pairs Im connecting to on Bittrex.  My guess is it is common SymbolOrderBook cache (or my use of it) rather than Bittrex specific.

Im starting a little digging of my own  but wanted to know if this is something you have seen or are working on?

Thanks

Ben

**Comment by JKorf** [comment]
It's not something I'm aware of. Are you by any chance doing some processing in the `OnOrderBookUpdate` event? I see that event handler is being called from inside a lock, which is a bit questionable. 
It would mean that as long as something is processing in the OnOrderBookUpdate event handler no new data can be processed in the order book, which would explain the message you're seeing.

**Comment by BenDavison** [comment]
Hi,

  There should not be any real load here, I post the update straight into
an mailbox which decouples the processing from the event itself.  I have
put some time aside this week to do some perf analysis on my application so
I will have a better picture if I am causing this issue. I am certainly
stressing the system with many pairs when this happens.

  I will let you know how it goes

  thanks

Ben
