### ISSUE TITLE
ApiProxy - difference btw BinanceClient and BinanceSocketClient in handling Host value

### ISSUE THREAD

**Issue by sewano** [JKorf/CryptoExchange.Net#32]
Encountered while working with Binance.Net 5.0.7 Nuget package, but the problem is within CryptoExchange.Net, thus submitting to CryptoExchange.Net issues.
Same problem with the lastest version cloned from master branch.

ApiProxy ctor requires host parameter to start with "http". From ApiProxy.cs:
<pre>if (!host.StartsWith("http"))
    throw new ArgumentException("Proxy host should start with either http:// or https://");
</pre>

It works fine for BinanceClient, but BinanceSocketClient attempts to DNS resolve this host value (starting with "http") and fails since "http://x.x.x.x" is not a valid host name.

Either ApiProxy shouldn't require host to start with "http" or BinanceSocketClient should properly chop protocol prefix from specified host value.

My current workaround is to add a fake host name to hosts file which starts with "http" and is resolved to HTTP proxy's IP.

**Comment by JKorf** [comment]
Hi, I've removed the check in the latest version, so that should work for you.

**Comment by sewano** [comment]
Yes, it works. Verified using Binance.Net 5.0.8 and also using lastest master branches of Binance.Net and CryptoExchange.Net.
Thank you!
