### ISSUE TITLE
Issues with GetOpenPositionsAsync() 

### ISSUE THREAD

**Issue by shotyme** [JKorf/CryptoExchange.Net#36]
Hi, 

I encountered an deserialization error while executing GetOpenPositionsAsync(). 

The issue is the field "maxNotionalValue" from the "positionRisk" endpoint.
For some reasons binance could return a string value here with the value "inf" (perhaps if the value is infinity).

Here is the json payload where one of the positions contains this value. The other positions have an integer value:

`"[{\"symbol\":\"BTCUSDT\",\"positionAmt\":\"0.000\",\"entryPrice\":\"0.00000\",\"markPrice\":\"6129.77693896\",\"unRealizedProfit\":\"0.00000000\",\"liquidationPrice\":\"0\",\"leverage\":\"10\",\"maxNotionalValue\":\"20000000\",\"marginType\":\"isolated\",\"isolatedMargin\":\"0.00000000\",\"isAutoAddMargin\":\"false\",\"positionSide\":\"BOTH\"},{\"symbol\":\"XRPUSDT\",\"positionAmt\":\"0.0\",\"entryPrice\":\"0.00000\",\"markPrice\":\"0.17314956\",\"unRealizedProfit\":\"0.00000000\",\"liquidationPrice\":\"0\",\"leverage\":\"20\",\"maxNotionalValue\":\"250000\",\"marginType\":\"cross\",\"isolatedMargin\":\"0.00000000\",\"isAutoAddMargin\":\"false\",\"positionSide\":\"BOTH\"},{\"symbol\":\"EOSUSDT\",\"positionAmt\":\"0.0\",\"entryPrice\":\"0.0000\",\"markPrice\":\"2.17963976\",\"unRealizedProfit\":\"0.00000000\",\"liquidationPrice\":\"0\",\"leverage\":\"10\",\"maxNotionalValue\":\"1000000\",\"marginType\":\"isolated\",\"isolatedMargin\":\"0.00000000\",\"isAutoAddMargin\":\"false\",\"positionSide\":\"BOTH\"},{\"sy
mbol\":\"LTCUSDT\",\"positionAmt\":\"0.000\",\"entryPrice\":\"0.00000\",\"markPrice\":\"38.36273888\",\"unRealizedProfit\":\"0.00000000\",\"liquidationPrice\":\"0\",\"leverage\":\"2\",\"maxNotionalValue\":\"inf\",\"marginType\":\"isolated\",\"isolatedMargin\":\"0.00000000\",\"isAutoAddMargin\":\"false\",\"positionSide\":\"BOTH\"},{\"symbol\":\"TRXUSDT\",\"positionAmt\":\"50\",\"entryPrice\":\"0.01111\",\"markPrice\":\"0.01111154\",\"unRealizedProfit\":\"0.00007700\",\"liquidationPrice\":\"0.01007\",\"leverage\":\"10\",\"maxNotionalValue\":\"1000000\",\"marginType\":\"isolated\",\"isolatedMargin\":\"0.05540480\",\"isAutoAddMargin\":\"false\",\"positionSide\":\"BOTH\"},{\"symbol\":\"ADAUSDT\",\"positionAmt\":\"0\",\"entryPrice\":\"0.00000\",\"markPrice\":\"0.02927060\",\"unRealizedProfit\":\"0.00000000\",\"liquidationPrice\":\"0\",\"leverage\":\"10\",\"maxNotionalValue\":\"1000000\",\"marginType\":\"isolated\",\"isolatedMargin\":\"0.00000000\",\"isAutoAddMargin\":\"false\",\"positionSide\":\"BOTH\"},{\"symbol\":
\"BATUSDT\",\"positionAmt\":\"0.0\",\"entryPrice\":\"0.00000\",\"markPrice\":\"0.13558396\",\"unRealizedProfit\":\"0.00000000\",\"liquidationPrice\":\"0\",\"leverage\":\"10\",\"maxNotionalValue\":\"100000\",\"marginType\":\"isolated\",\"isolatedMargin\":\"0.00000000\",\"isAutoAddMargin\":\"false\",\"positionSide\":\"BOTH\"}]"
`

I fixed the issue in my version by changing the property "MaxNotionalValue" from decimal to string

**EDIT:**

This issue occurs in the method "ChangeMarginTypeAsync()" too, because the result type contains the "MaxNotionalValue" as well. A change to string fix that.

**Comment by JKorf** [comment]
Hi, I've fixed this issue in Binance version 5.1.1, thanks for the report :)
For next time, please post the issues related to specific exchange implementations on the correct github repo instead of the base.
