### ISSUE TITLE
ChangeMarginTypeAsync() & ChangeInitialLeverageAsync() not working

### ISSUE THREAD

**Issue by shotyme** [JKorf/CryptoExchange.Net#37]
The mentioned endpoints are currently not working because the library calls them with a GET request but this are POST endpoints. Change this line:

`return await SendRequest<BinanceFuturesChangeMarginTypeResult>(GetUrl(ChangeMarginTypeEndpoint, Api, SignedVersion), HttpMethod.Get, ct, parameters, true).ConfigureAwait(false);
`

`return await SendRequest<BinanceFuturesInitialLeverageChangeResult>(GetUrl(ChangeInitialLeverageEndpoint, Api, SignedVersion), HttpMethod.Get, ct, parameters, true).ConfigureAwait(false);`

to 

`return await SendRequest<BinanceFuturesChangeMarginTypeResult>(GetUrl(ChangeMarginTypeEndpoint, Api, SignedVersion), HttpMethod.Post, ct, parameters, true).ConfigureAwait(false);
`

`return await SendRequest<BinanceFuturesInitialLeverageChangeResult>(GetUrl(ChangeInitialLeverageEndpoint, Api, SignedVersion), HttpMethod.Post, ct, parameters, true).ConfigureAwait(false);`

and it works!

**Comment by JKorf** [comment]
Hi, I've fixed this issue in Binance version 5.1.1, thanks for the report :)
