### ISSUE TITLE
Protocol Buffers and CryptoExchange.Net

### ISSUE THREAD

**Issue by PhilAlain** [JKorf/CryptoExchange.Net#39]
We are developping a websocket api for Livecoin.net marketplace.
The messages are based on google's protocol buffer messages : https://developers.google.com/protocol-buffers

Are there any plans to integrate protocol buffer messages as part of CryptoExchange.net ?
What would be the best route for this implementation (based on CryptoExchange.net)

**Comment by JKorf** [comment]
Hi, 

I have to say I'm not familiar with protocol buffers, but having a quick look at them it seems like it would take quite some effort to integrate it. Frankly I don't have enough time at the moment to look into that at the moment. 

If wou want to take a go at it yourself, I'm always open to PRs.
