### ISSUE TITLE
3.0.14 not working Kucoin Order book and Kraken problemas =(

### ISSUE THREAD

**Issue by MatheusGrijo** [JKorf/CryptoExchange.Net#49]
In the update of 3.0.14, the KUCOIN ordebook stopped working, and Kraken is giving an error in the Orderbook too, I had to go back to version 3.0.12 where everything works normally.

**Comment by JKorf** [comment]
Is expected, I'm still in the process of updating the implementations. Will be fixed in the next update.

**Comment by JKorf** [comment]
All implementations should work with 3.0.14 now (Binance beta version only)
