### ISSUE TITLE
Projects driven by CryptoExchange, and community 

### ISSUE THREAD

**Issue by novecento** [JKorf/CryptoExchange.Net#51]
Hi again,
do we have a public list of projects where CryptoExchange is used?
Have you already thought about building a community? (discord, telegram, or other?)

**Comment by Tr0sT** [comment]
Yes, how about creating a discord server?

**Comment by novecento** [comment]
why not!

**Comment by JKorf** [comment]
I know it's been a while, but I've actually set up a Discord server just now: https://discord.gg/MSpeEtSY8t, feel free to join
