### ISSUE TITLE
Attention JKorf: Please can this project enforce semantic versioning?

### ISSUE THREAD

**Issue by daniel-levin** [JKorf/CryptoExchange.Net#56]
Hi there!

I am an avid consumer of both CryptoExchange.NET and the derivative projects. I first would like to say that I enjoy using them and appreciate the work very much.

My app depends on several of them. I understand that you maintain most implementations, but some, such as [OKEx.NET](https://github.com/burakoner/OKEx.Net/) depend on CryptoExchange.Net. 

As you are no doubt aware, there were breaking changes from NuGet package version `3.0.5` to version `3.0.14`. Might I suggest that API-breaking changes result in an increment of the major number in the NuGet package?

Also, while we are on the topic of versioning, .NET ambiguously allows NuGet package versions to differ from assembly versions. Please can you also enforce semantic versioning of the assembly version? It does not appear to be set by default, and is `1.0.0.0` across multiple, incompatible versions.

**Comment by JKorf** [comment]
You're right, I'll try to be more precise with the version numbers.

I'll have a look at the assembly versions as well.
