### ISSUE TITLE
file list with keys not work

### ISSUE THREAD

**Issue by xazes** [JKorf/CryptoExchange.Net#57]
Hi
I would use the CryptoExchange.Net.Authentication.ApiCredentials with file json list:
`{  
	"binanceKey":"actualBinanceApiKey",
	"binanceSecret":"actualBinanceApiSecret",
	"bittrexKey":"actualBittrexApiKey",
	"bittrexSecret":"actualBittrexApiSecret"
}`

but he tells me that an invalid json format. I debug the 
using var reader = new StreamReader(inputStream, Encoding.ASCII, false, 512, true);
            
            var stringData = reader.ReadToEnd(); <--- the stringdata conatains three ??? at first signs
            var jsonData = stringData.ToJToken();

**Comment by JKorf** [comment]
Seems to work fine for me. Make sure there aren't any weird or invisible characters in the file. Try saving it specifically in ASCII and see if that works.

**Comment by xazes** [comment]
i have make a normal txt file with code from your readme. when i turn encoding.ascii to utf8 it works.

**Comment by JKorf** [comment]
I've changed encoding of the reader to UTF8, so I think it should also work with your original file.
