### ISSUE TITLE
Binance spot URL construction

### ISSUE THREAD

**Issue by MartyIX** [JKorf/CryptoExchange.Net#63]
It looks like this commit https://github.com/JKorf/CryptoExchange.Net/commit/47a1e0bef8b117d855b184de6cdb4252af89c8c1 breaks https://github.com/JKorf/Binance.Net/blob/5231d56006c1c26a107cbf9f3f6bf5302cb476a0/Binance.Net/BinanceClient.cs#L264.

**Comment by MartyIX** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.uri.-ctor?view=netcore-3.1#System_Uri__ctor_System_Uri_System_String_ - I think it would be safer to construct URIs using constructor `public Uri (Uri baseUri, string? relativeUri);` which checks that the final URI is correct or throws an exception.

**Comment by JKorf** [comment]
Latest version of the libraries should work okay.

You're right though, should probably use the Uri class.
