### ISSUE TITLE
"Can't connect to the server" when doing multiple SymbolOrderBook requests

### ISSUE THREAD

**Issue by kyriakosBak** [JKorf/CryptoExchange.Net#64]
First of all I would like to thank you for this amazing project.

I try to fetch all the orderbooks for different exchanges using SymbolOrderBook. In order to achieve that, I get all the symbols for an exchange and for each of them I do a SymbolOrderBook.StartAsync(). 

I keep getting a "Can't connect to the server" error message which I don't get when I try to retrieve retrieve a small number (10) of SymbolOrderBook. In the output window of VS I start getting messages for sockets closed. 

![image](https://user-images.githubusercontent.com/10158477/100549702-dcfb8b80-3274-11eb-848b-83396e661c2c.png)

Let me know if you need any more information or have any suggestion/solution.

**Comment by JKorf** [comment]
How many books are you trying to connect? And on what exchanges?

**Comment by kyriakosBak** [comment]
I try to subscribe to everything in Binance

**Comment by JKorf** [comment]
That's a lot of connections. To save connections consider combining multiple symbols in a single subscribe call, most of the subscribe calls accept an IEnumerable<string> for symbols. Every subscribe call will create a socket connection, so combining subscribe calls might help. Let me know.

**Comment by kyriakosBak** [comment]
I see. So I guess I cannot use the SymbolOrderBook and need to go down the SubscribeToOrderBookUpdates way.
