### ISSUE TITLE
Add a UpdateSubscription<T> for subscribe API with a return value

### ISSUE THREAD

**Issue by EricGarnier** [JKorf/CryptoExchange.Net#66]
Hi,
during the development of LiveCoin.NET, I needed to return a value from the subscribe call. This is du to the API design of LiveCoin.

So I created this type UpdateSubscription< T >  

`public class UpdateSubscription<T> : CryptoExchange.Net.Sockets.UpdateSubscription where T : class`

with a property 

`		/// <summary>`
`		/// Server answer`
`		/// </summary>`
`		public T? SubscriptionResponse { get; set; }
`

Maybe it would be a good idea to move this in CryptoExchange.Net.

Have a look here : [https://github.com/EricGarnier/LiveCoin.Net/blob/master/LiveCoin.Net/Sockets/UpdateSubscription.cs](url)

Thanks.
Eric

**Comment by ridicoulous** [comment]
Hello @EricGarnier.
I believe you can use `SendAndWait<T>(T obj, TimeSpan timeout, Func<JToken, bool> handler);` method at `SocketConnection` instance

**Comment by EricGarnier** [comment]
Hello @ridicoulous 
I rewrite a `Task<CallResult<UpdateSubscription<V>>> Subscribe<T, V>` in my LiveCoinSocketClient.
You can have a look here : 
[https://github.com/EricGarnier/LiveCoin.Net/blob/7f77c63ae8c5605f1c738d613df3fc92d35054c9/LiveCoin.Net/LiveCoinSocketClient.cs#L121](https://github.com/EricGarnier/LiveCoin.Net/blob/7f77c63ae8c5605f1c738d613df3fc92d35054c9/LiveCoin.Net/LiveCoinSocketClient.cs#L121)


I don't see how to use `SendAndWait<T>(T obj, TimeSpan timeout, Func<JToken, bool> handler);  method` at `SocketConnection` instance.

My point was just that maybe it could be a good idea to integrate this type in CryptoExchange.Net, as it can be a share need.

Eric

**Comment by JKorf** [comment]
Hi @EricGarnier, I think a goal for libraries based on CryptoExchange.Net should be that they all work in a similar way. I'm not too big of a fan of returning data of the subscribe call. You could maybe consider calling the data handler with the request result if the data is compatible?

**Comment by EricGarnier** [comment]
Hi @JKorf ,
I understand. Not sure it is always possible. I will try.

Thanks.
