### ISSUE TITLE
RateLimiterAPIKey keeps API keys in a plain text while ApiCredentials as a SecureString

### ISSUE THREAD

**Issue by ziez** [JKorf/CryptoExchange.Net#67]
Hey! I'm wondering if it was done intentionally to keep API key as a plain text in the RateLimiterAPIKey.history dictionary?
It looks like the RateLimiter has the same lifetime as the ApiCredentials having the string unsecure here might be an issue.

My suggestion would be using either hash of the key or SecureString instance as a key.

**Comment by ridicoulous** [comment]
Hello, @ziez!

I believe it isn't a something horrible, cause the secret key is in safe and many exchanges passes this keys in request url

**Comment by JKorf** [comment]
Hi, you're right @ridicoulous , it's not  a big offence, but it wasn't correct. I've changed it to use a hash of the key instead.
