### ISSUE TITLE
Reconnection issue

### ISSUE THREAD

**Issue by miqteam** [JKorf/CryptoExchange.Net#68]
If my internet connection goes down, after a while i can get data from client socket. But when i check logs, i see that it tries to reconnect all the time even i can get data.
Here is the log after i get connected :

2020.12.10 23:37:40.3886 : Binance - 2020.12.10 23:37:40:388 | Info | Socket 27 reconnected after 00:00:06.0993857
2020.12.10 23:37:44.8641 : Binance - 2020.12.10 23:37:44:864 | Warning | No data received for 00:00:20, reconnecting socket
2020.12.10 23:37:45.1965 : Binance - 2020.12.10 23:37:45:196 | Info | Socket 1 Connection lost, will try to reconnect after 00:00:05
2020.12.10 23:37:45.8805 : Binance - 2020.12.10 23:37:45:880 | Warning | No data received for 00:00:20, reconnecting socket
2020.12.10 23:37:45.9036 : Binance - 2020.12.10 23:37:45:903 | Info | Socket 7 reconnected after 00:00:06.1142623
2020.12.10 23:37:46.2538 : Binance - 2020.12.10 23:37:46:253 | Info | Socket 5 Connection lost, will try to reconnect after 00:00:05
2020.12.10 23:37:50.9244 : Binance - 2020.12.10 23:37:50:924 | Warning | No data received for 00:00:20, reconnecting socket
2020.12.10 23:37:51.2017 : Binance - 2020.12.10 23:37:51:201 | Info | Socket 2 Connection lost, will try to reconnect after 00:00:05
2020.12.10 23:37:51.3551 : Binance - 2020.12.10 23:37:51:355 | Info | Socket 1 reconnected after 00:00:06.1586506
2020.12.10 23:37:52.4126 : Binance - 2020.12.10 23:37:52:412 | Info | Socket 5 reconnected after 00:00:06.1587551
2020.12.10 23:37:55.6912 : Binance - 2020.12.10 23:37:55:691 | Warning | No data received for 00:00:20, reconnecting socket
2020.12.10 23:37:56.0367 : Binance - 2020.12.10 23:37:56:036 | Info | Socket 26 Connection lost, will try to reconnect after 00:00:05
2020.12.10 23:37:57.1593 : Binance - 2020.12.10 23:37:57:159 | Warning | No data received for 00:00:20, reconnecting socket
2020.12.10 23:37:57.3122 : Binance - 2020.12.10 23:37:57:312 | Info | Socket 2 reconnected after 00:00:06.1104772
2020.12.10 23:37:57.4667 : Binance - 2020.12.10 23:37:57:466 | Info | Socket 3 Connection lost, will try to reconnect after 00:00:05
2020.12.10 23:38:00.4735 : Binance - 2020.12.10 23:38:00:473 | Warning | No data received for 00:00:20, reconnecting socket
2020.12.10 23:38:00.7467 : Binance - 2020.12.10 23:38:00:746 | Info | Socket 6 Connection lost, will try to reconnect after 00:00:05
2020.12.10 23:38:02.2421 : Binance - 2020.12.10 23:38:02:242 | Info | Socket 26 reconnected after 00:00:06.2054164
2020.12.10 23:38:03.6086 : Binance - 2020.12.10 23:38:03:608 | Info | Socket 3 reconnected after 00:00:06.1419027
2020.12.10 23:38:06.0329 : Binance - 2020.12.10 23:38:06:032 | Warning | No data received for 00:00:20, reconnecting socket
2020.12.10 23:38:06.4585 : Binance - 2020.12.10 23:38:06:458 | Info | Socket 7 Connection lost, will try to reconnect after 00:00:05
2020.12.10 23:38:06.8372 : Binance - 2020.12.10 23:38:06:837 | Info | Socket 6 reconnected after 00:00:06.0904978
2020.12.10 23:38:12.5472 : Binance - 2020.12.10 23:38:12:547 | Info | Socket 7 reconnected after 00:00:06.0886499
2020.12.10 23:38:12.5962 : Binance - 2020.12.10 23:38:12:596 | Warning | No data received for 00:00:20, reconnecting socket
2020.12.10 23:38:12.9971 : Binance - 2020.12.10 23:38:12:997 | Info | Socket 5 Connection lost, will try to reconnect after 00:00:05
2020.12.10 23:38:19.1650 : Binance - 2020.12.10 23:38:19:165 | Info | Socket 5 reconnected after 00:00:06.1680516
2020.12.10 23:38:22.7089 : Binance - 2020.12.10 23:38:22:708 | Warning | No data received for 00:00:20, reconnecting socket
2020.12.10 23:38:22.7782 : Binance - 2020.12.10 23:38:22:778 | Warning | No data received for 00:00:20, reconnecting socket
2020.12.10 23:38:22.9988 : Binance - 2020.12.10 23:38:22:998 | Info | Socket 26 Connection lost, will try to reconnect after 00:00:05
2020.12.10 23:38:23.0680 : Binance - 2020.12.10 23:38:23:068 | Info | Socket 1 Connection lost, will try to reconnect after 00:00:05
2020.12.10 23:38:23.8011 : Binance - 2020.12.10 23:38:23:800 | Warning | No data received for 00:00:20, reconnecting socket
2020.12.10 23:38:24.1686 : Binance - 2020.12.10 23:38:24:168 | Info | Socket 3 Connection lost, will try to reconnect after 00:00:05

**Comment by ridicoulous** [comment]
Hello @miqteam 

As I can see in logs, you setted `SocketNoDataTimeout` parameter  of socket client to 20 seconds. It means that socket considers brocked if it does not catch any message in this time period and going to reconnect.  

So, for example, if you listen to trades endpoint at low liquidity market with one trade in minute with `SocketNoDataTimeout=TimeSpan.FromSeconds(10)`,  at logs you will see 5-6 reconnects each minute

**Comment by miqteam** [comment]
Hi,
I get these logs with market data. I use this socket connection to get market depth and tick data. So there souldn't be a scenerio about not cathcing any data.

**Comment by JKorf** [comment]
The socket only sends data if anything in the data it represents changes. For market data you can't really guarantee that anything changes at least every 20 seconds. A lot of markets with high liquidity will, but some with lower liquidity will not. 

The SocketNoDataTimeout which you set to 20 seconds is mainly used for exchanges where there is a ping/pong mechanism. For example, all Bitfinex socket connections will send a ping message every 15 seconds. So if nothing is received for +- 20 seconds you know something is wrong and try to reconnect. For Binance, where there is no such mechanism, this isn't really usable.
