### ISSUE TITLE
Questions and suggestions

### ISSUE THREAD

**Issue by nikkozp** [JKorf/CryptoExchange.Net#7]
Hey. There are some questions.

1) client.AddRateLimiter() a limit on the number of requests? for example, for Binance I need to declare it as a client.AddRateLimiter(new RateLimiterTotal (20, TimeSpan.FromSeconds (1))) ?
And if that's all right, can you add an event to the number of requests executed per second?

2) you can add to client.Ping() ping time. For example client.Ping(out int ping)

3) I'm trying to update CryptoExchange.Net to v0.0.36 but I can't. Because dependencies cannot be resolved. "CryptoExchange.Net 0.0.36" not compatible with Binance.Net 3.1.15 limitation: CryptoExchange.Net (=0.0.31). Is it supposed to?

**Comment by JKorf** [comment]
Hi,
1. That is how it works yes. The behaviour can also be configured by setting the RateLimittingBehaviour in the options of the client. There is no event or property for number of requests per seconds, and I feed like that is up to the client to handle.
2. As you might have seen I've added a ping method.
3. Because the CryptoExchange.Net interface might change I put a restraint on the version for specific clients. I've removed that restraint for now as I don't have any interface changes planned. Latest client versions should work with latest CryptoExchange.Net

**Comment by nikkozp** [comment]
1.I took it from you to UnitTest.
```
public void WhenUsingRateLimiterPerEndpointRequests_Should_BeDelayed()
        {
            // arrange
            var client = PrepareClient(JsonConvert.SerializeObject(new TestObject()));
            client.AddRateLimiter(new RateLimiterTotal(1, TimeSpan.FromSeconds(5)));
            // act
            var sw = Stopwatch.StartNew();
            client.TestCall();
            client.TestCall();
            client.TestCall();
            sw.Stop();

            // assert
            Assert.IsTrue(sw.ElapsedMilliseconds > 9000);
        }
```
If I understand correctly, it makes 1 request every 5 seconds.

I want to make a `client.AddRateLimiter(new RateLimiterTotal (20, TimeSpan.FromSeconds(1)));` 20 requests per second.

And now a question/suggestion.

Can I know the number of requests at any time of the program that would know how fast the program works?

Most likely you only need to `return history.Count`

2. Thx
3. Thx

**Comment by JKorf** [comment]
I don't really plan on adding anything to know the current request rate, but you can easily add it yourself. You can make your own rate limiter based on the existing one using the IRateLimiter interface which could return the requests per seconds:
````C#
    public class CustomLimiter :IRateLimiter
    {
        internal List<DateTime> history = new List<DateTime>();

        private readonly int limit;
        private readonly TimeSpan perTimePeriod;
        private readonly object requestLock = new object();

        public double CallsPerSecond
        {
            get { return history.Count() / perTimePeriod.TotalSeconds; }
        }

        /// <summary>
        /// Create a new RateLimiterTotal. This rate limiter limits the amount of requests per time period to a certain limit, counts the total amount of requests.
        /// </summary>
        /// <param name="limit">The amount to limit to</param>
        /// <param name="perTimePeriod">The time period over which the limit counts</param>
        public CustomLimiter(int limit, TimeSpan perTimePeriod)
        {
            this.limit = limit;
            this.perTimePeriod = perTimePeriod;
        }

        public CallResult<double> LimitRequest(string url, RateLimitingBehaviour limitBehaviour)
        {
            var sw = Stopwatch.StartNew();
            lock (requestLock)
            {
                sw.Stop();
                double waitTime = 0;
                var checkTime = DateTime.UtcNow;
                history.RemoveAll(d => d < checkTime - perTimePeriod);

                if (history.Count >= limit)
                {
                    waitTime = (history.First() - (checkTime - perTimePeriod)).TotalMilliseconds;
                    if (waitTime > 0)
                    {
                        if (limitBehaviour == RateLimitingBehaviour.Fail)
                            return new CallResult<double>(waitTime, new RateLimitError($"total limit of {limit} reached"));

                        Thread.Sleep(Convert.ToInt32(waitTime));
                        waitTime += sw.ElapsedMilliseconds;
                    }
                }

                history.Add(DateTime.UtcNow);
                history.Sort();
                return new CallResult<double>(waitTime, null);
            }
        }
    }
````
You can then use this to get the current requests:
````C#
    var rl = new CustomLimiter(20, TimeSpan.FromSeconds(1));
    client.AddRateLimiter(rl);

    // start doing stuff .. 

    Console.WriteLine("Calls per seconds: " + rl.CallsPerSecond);
````
