### ISSUE TITLE
After a pending request timeout, the next message is silently ignored

### ISSUE THREAD

**Issue by EricGarnier** [JKorf/CryptoExchange.Net#71]
On a socket client, when a request time out, the next message is not properly processed.
To reproduce, the scenario is the following.
1) on a `SocketConnection` send a request with `SendAndWait`. This add a `PendingRequest` to the `pendingRequests` list, and return a `pending.Event.WaitOneAsync(timeout)`

`            var pending = new PendingRequest(handler, timeout);`
`            pendingRequests.Add(pending);`
`            Send(obj);`
`            return pending.Event.WaitOneAsync(timeout);`

2) the server never respond, so the `pending.Event.WaitOneAsync(timeout)` return, and the normal processing continue. But the `PendingRequest` is still in the  `pendingRequests` list;

3) the server send an unrelated message. This message is passed to the `Check` method of  the `PendingRequest` still in the  `pendingRequests` list. This method detects the timeout condition, and return true.
`            if (DateTime.UtcNow - startTime > Timeout)`
`            {`
`                // Timed out`
`                Event.Set();`
`                return true;`
`            }`

4) the controlling loop in `ProcessMessage` break, and stop processing the message. It is lost.
`            foreach (var pendingRequest in pendingRequests.ToList())`
`            {`
`                if (pendingRequest.Check(tokenData))`
`                {`
`                    pendingRequests.Remove(pendingRequest);`
`                    if (!socketClient.ContinueOnQueryResponse)`
`                        return;`
`                    handledResponse = true;`
`                    break;`

I will try to propose a fix for this. #72 

Eric

**Comment by JKorf** [comment]
You're right, good find. Thanks for including a fix as well.
