### ISSUE TITLE
ClientOptions BaseAddress Ending Slash Problem

### ISSUE THREAD

**Issue by burakoner** [JKorf/CryptoExchange.Net#74]
I am developing a SDK for bitmax.io. I have a problem with websocket client. Because bitmax.io ws feed url doesnt end with a slash and It give 404 error if I put slash. But on ClientOptions (CryptoExchange.Net.Objects.ClientOptions) there is a rule for ending with slash.

Is there a way to remove ending slash in BaseAddress?

Working Url: wss://bitmax.io/1/api/pro/v1/stream
Not Working Url: wss://bitmax.io/1/api/pro/v1/stream/

**Comment by JKorf** [comment]
Hi, I think it should work when you override the CreateSocket method in your socket client right? Just strip the slash of the end when creating the socket. Something like this:
````C#
protected override IWebsocket CreateSocket(string address)
{
    address = address.TrimEnd('/');
    var socket = SocketFactory.CreateWebsocket(log, address);
    log.Write(LogVerbosity.Debug, "Created new socket for " + address);

    if (apiProxy != null)
        socket.SetProxy(apiProxy.Host, apiProxy.Port);

    socket.Timeout = SocketNoDataTimeout;
    socket.DataInterpreterBytes = dataInterpreterBytes;
    socket.DataInterpreterString = dataInterpreterString;
    socket.OnError += e =>
    {
        log.Write(LogVerbosity.Info, $"Socket {socket.Id} error: " + e);
    };
    return socket;
}
````

**Comment by burakoner** [comment]
Yup. I did it with override already. But I think it will be good if there is an option to add slash suffix
