### ISSUE TITLE
Ftx Authentication

### ISSUE THREAD

**Issue by tenebriox** [JKorf/CryptoExchange.Net#76]
Hi,
I'm trying to implement ftx exchange API, I inspired a lot from the existing implementations and get it almost working.
My problem is about the authenticated requests, I cannot get them, still getting "Server error: Received error from server...:{
  "error": "Not logged in",
  "success": false
} "
This sample is working fine : 

httpClient = new HttpClient
           {
               BaseAddress = new Uri("https://ftx.com/"),
               Timeout = TimeSpan.FromSeconds(30)
           };
           _hashMaker = new HMACSHA256(Encoding.UTF8.GetBytes("api-secret"));
           var account = GetAccountInfoAsync();

public async Task<dynamic> GetAccountInfoAsync()
        {
            var resultString = $"api/account";
            var sign = GenerateSignature(HttpMethod.Get, "/api/account", "");

            var result = await CallAsyncSign(HttpMethod.Get, resultString, sign);

            return ParseResponce(result);
        }

        private dynamic ParseResponce(string responce)
        {
            return (dynamic)responce;
        }

        private async Task<string> CallAsyncSign(HttpMethod method, string endpoint, string sign, string body = null)
        {
            var request = new HttpRequestMessage(method, endpoint);

            if (body != null)
            {
                request.Content = new StringContent(body, Encoding.UTF8, "application/json");
            }

            request.Headers.Add("FTX-KEY", "api-key");
            request.Headers.Add("FTX-SIGN", sign);
            request.Headers.Add("FTX-TS", _nonce.ToString());

            var response = await _httpClient.SendAsync(request).ConfigureAwait(false);

            var result = await response.Content.ReadAsStringAsync().ConfigureAwait(false);

            return result;
        }

        private string GenerateSignature(HttpMethod method, string url, string requestBody)
        {
            _nonce = GetNonce();
            var signature = $"{_nonce}{method.ToString().ToUpper()}{url}{requestBody}";
            var hash = _hashMaker.ComputeHash(Encoding.UTF8.GetBytes(signature));
            var hashStringBase64 = BitConverter.ToString(hash).Replace("-", string.Empty);
            return hashStringBase64.ToLower();
        }
        private readonly HMACSHA256 _hashMaker;
        private long _nonce;
        private HttpClient _httpClient;

        private long GetNonce()
        {
            return Util.GetMillisecondsFromEpochStart();
        }

**And my implementation for the FtxAuthenticationProvider  cryptoexchange.net is the following:**
`internal class FtxAuthenticationProvider : AuthenticationProvider
    {
        private readonly HMACSHA256 _hashMaker;
        private long _nonce;

        public FtxAuthenticationProvider(ApiCredentials credentials) : base(credentials)
        {
            if (credentials.Secret == null)
                throw new ArgumentException("No valid API credentials provided. Key/Secret needed.");

            string secret = new System.Net.NetworkCredential(string.Empty, Credentials.Secret).Password;

            _hashMaker = new HMACSHA256(Encoding.UTF8.GetBytes(secret));
        }

        public override Dictionary<string, object> AddAuthenticationToParameters(string uri, HttpMethod method, Dictionary<string, object> parameters, bool signed, PostParameters postParameterPosition, ArrayParametersSerialization arraySerialization)
        {
            //Nothing
            return parameters;
        }
       

        private string GenerateSignature(HttpMethod method, string url, string requestBody)
        {
            
            _nonce = GetNonce();
            var signature = $"{_nonce}{method.ToString().ToUpper()}{url}{requestBody}";
            var hash = _hashMaker.ComputeHash(Encoding.UTF8.GetBytes(signature));
            var hashStringBase64 = BitConverter.ToString(hash).Replace("-", string.Empty);
            return hashStringBase64.ToLower();
        }

        private long GetNonce()
        {
            return Util.Util.GetMillisecondsFromEpochStart();
        }

        public override Dictionary<string, string> AddAuthenticationToHeaders(string uri, HttpMethod method, Dictionary<string, object> parameters, bool signed, PostParameters postParameterPosition, ArrayParametersSerialization arraySerialization)
        {
            if (Credentials.Key == null)
                throw new ArgumentException("No valid API credentials provided. Key/Secret needed.");
            string key = new System.Net.NetworkCredential(string.Empty, Credentials.Key).Password;
            
            string signature = GenerateSignature(method, uri, "");
            return new Dictionary<string, string>
            {
               
               
                { "FTX-KEY", key },
                { "FTX-SIGN",signature },
                { "FTX-TS",_nonce.ToString() }
            };

        }
    }`

Does someone already realized that or have any idea from where the problem could be ?

**Comment by ridicoulous** [comment]
You can take look [here](https://github.com/ridicoulous/Ftx.Net)
In near future I'll will work with it

**Comment by tenebriox** [comment]
Waow..... Can't thank you enough for the answer @ridicoulous, it's awesome you already did the job  👍 
I already searched exactly for that, but didn't find anything, so I wasn't expecting such a good news!
I will let you know if I find issues and I will contribute if I can.
I close the thread, thank you again, you made my day ! 💯

**Comment by ridicoulous** [comment]
@tenebriox contributions are welcome!
