### ISSUE TITLE
RestClient.GetResponse private to protected

### ISSUE THREAD

**Issue by valvv** [JKorf/CryptoExchange.Net#77]
Hi,
I need to create custom POST responce instead of SendRequest with both PostParameters.InUri and PostParameters.Post parameters. I can use ConstructRequest and WriteParamBody, However, it will be nice to move RestClient.GetResponse to protected to use it after ConstructRequest 
Thanks

**Comment by JKorf** [comment]
I'm not sure if I understand the issue.

**Comment by valvv** [comment]
I need both Uri and InBody PostParameters in 1 request.
So I can't use SendRequest function
I can do it this way:
CryptoExchange.Net.Interfaces.IRequest request = base.ConstructRequest(uri, httpMethod, uriParams, signed, PostParameters.InUri, ArrayParametersSerialization.Array, 0);
WriteParamBody(request, bodyParamst, Constants.JsonContentHeader);
return await GetResponse<T>(request);

However GetResponse is private. Please, do it protected

**Comment by JKorf** [comment]
I've changed it to virtual protected in the latest version

**Comment by valvv** [comment]
Thanks
