### ISSUE TITLE
High CPU usage when subscribed to full depth for a number of instruments

### ISSUE THREAD

**Issue by tekr** [JKorf/CryptoExchange.Net#82]
Using the OkEx wrapper (from [here](https://github.com/burakoner/OKEx.Net)) built on top of this library, I observe very high CPU usage when subscribed to updates for relatively few order books (~20, while OkEx has hundreds of instruments available). This really limits the scalability of any system using this library for handling a large number of messages.

Profiling shows that over half our market data recorder's total CPU time is spent inside ArrayConverter.ParseObject(), and mostly calling System.Attribute.GetCustomAttributes() (see highlighted line in below screenshot).

![ArrayConverterPerfBeforeOptimisation](https://user-images.githubusercontent.com/6520630/110457570-bd8ebd00-8105-11eb-9372-cb7a049334f6.png)

Custom attributes do not change at runtime, hence a cache is likely to hugely improve performance here. I'll have a go at it.

**Comment by JKorf** [comment]
This is available in version 3.7.1.
