### ISSUE TITLE
No help unless documentation provided

### ISSUE THREAD

**Issue by ronin225** [JKorf/CryptoExchange.Net#84]
This is exactly the type of thing I'm looking for, spent all day trying to get an API working.

You must of spent hours writing this code, and I would LOVE to donate, but it seems you don't want anyone to use your code unless they are professional programmers.

I as a trader would of donated, but you havent even spent an hour putting up a video on how to get started or anything.

**Comment by Marini83** [comment]
Well github is mostly for programmers, can't author for that.

**Comment by JKorf** [comment]
For last update I've spend a decent amount of time on documentation, which is available on the different github.io pages. For example:
https://jkorf.github.io/CryptoExchange.Net/
https://jkorf.github.io/Binance.Net/
https://jkorf.github.io/Kucoin.Net/

If any anyone is missing some documentation let me know and I'll look into adding it
