### ISSUE TITLE
Sometimes get "Message not handled" in log for socket client

### ISSUE THREAD

**Issue by DanTheManGC** [JKorf/CryptoExchange.Net#85]
Hi Jan.  Thank you for creating, sharing and ongoing contributions to these projects!

When using BinanceSocketClient with logging enabled and verbosity CryptoExchange.Net.Logging.LogVerbosity.Warning, I sometimes get a log entry with "Message not handled".  Here is an example...

2021/03/17 02:02:20:832 | Binance    | Warning | Message not handled: {
  "stream": "lrcbtc@bookTicker",
  "data": {
    "u": 199622853,
    "s": "LRCBTC",
    "b": "0.00000981",
    "B": "605.00000000",
    "a": "0.00000996",
    "A": "340.00000000"
  }
}

Can you please explain what causes these warnings and whether they can be avoided?  I couldn't work it out.

**Comment by JKorf** [comment]
These warnings happen when a message is received on the websocket but there was no one to process the specific message. This could happen when unsubscribing due to the handler being removed before the unsubscription was completed. This should be fixed in the latest beta releases

**Comment by DanTheManGC** [comment]
Great, thanks Jan!
