### ISSUE TITLE
WebSocket Client is outdated。

### ISSUE THREAD

**Issue by CIRCLE2096** [JKorf/CryptoExchange.Net#87]
The WebSocket Client([WebSocket4Net](https://www.nuget.org/packages/WebSocket4Net)) that CryptoExchange.Net used is outdated, it haven't been updated since 2018, and the current version doesn't work well with proxy. Is it possible to change it to Websocket.Client(https://github.com/Marfusios/websocket-client) or some other active websocket client project?

**Comment by JKorf** [comment]
The reason I used WebSocket4Net is that it worked on Windows 7 machines where the native websocket implementation wasn't available. But since Windows 7 is no long supported and Windows 10 has been the standard for some time, I think it might be time to update this.

I'll look into it.

**Comment by JKorf** [comment]
I've created a beta version using the dotnet ClientWebSocket instead of WebSocket4Net, you can try it. Use the beta version of the implementations and use the latest beta version of CryptoExchange.Net (beta3 atm). You'll need to manually ref beta3, the implementations still reference beta1.

**Comment by novecento** [comment]
> I've created a beta version using the dotnet ClientWebSocket instead of WebSocket4Net, you can try it. Use the beta version of the implementations and use the latest beta version of CryptoExchange.Net (beta3 atm). You'll need to manually ref beta3, the implementations still reference beta1.

what is your feeling, what do you think about?

**Comment by JKorf** [comment]
I've been using the ClientWebsocket implementation for a while in my own project now, seems to work fine.

**Comment by JKorf** [comment]
Latest releases are no longer dependent on Websocket4Net
