### ISSUE TITLE
symbol: invalid in PlaceOrderAsync on Bitfinex client

### ISSUE THREAD

**Issue by heavymanto** [JKorf/CryptoExchange.Net#88]
Hi, i have test to pace an order on Bitfinex client with PlaceOrderAsync method but it respond aways "symbol: invalid". I have check that data in input are correct "tTRXBTC" as exchange specification. i have funds in both accounts.

CODE
```
string _symbol = ((IExchangeClient)_client).GetSymbolName(_valutaBase, _valutaQuote);
IExchangeClient.OrderSide _operation = (IExchangeClient.OrderSide)(int)operation;

var order = ((IExchangeClient)_client).PlaceOrderAsync(_symbol, _operation, IExchangeClient.OrderType.Market, amount);
```

DATA/LOG OF ORDER RESULT
debugData --> **symbol**: tTRXBTC, **operation**: Buy, **amount**: 480.538203
ApiClient_Bitfinex.PlaceOrder --> InternalServerError,symbol: invalid

**Comment by heavymanto** [comment]
i have found problem, it work if you use OrderType.ExchangeMarket instead OrderType.Market

`var order = _client.PlaceOrderAsync(_symbol, _operation, OrderType.ExchangeMarket, 0, Math.Round(amount,4));`

There is a BUG in IExchangeClient.PlaceOrderAsync because GetOrderType map Market. This fix It

`if (type == IExchangeClient.OrderType.Market) return OrderType.ExchangeMarket;`

**Comment by JKorf** [comment]
Has been fixed in the beta release
