### ISSUE TITLE
New API restrictions on Binance

### ISSUE THREAD

**Issue by LaroCroft** [JKorf/CryptoExchange.Net#91]
Binance has increased the API restrictions at the end of April. As Binance API is not able to get all orders for all symbols within a specific time span I have to pull for each symbol. This leads to a ban very quickly...

I was checking the rate limiters but they only give me the opportunity to set rates based on time or amount of requests. Binance is using weights for each request and they also return the time to wait as response.

Are there any plans to implement a rate limiter based on weights?

**Comment by LaroCroft** [comment]
I dove a bit deeper in the code and tried to create my own rate limiter. But the problem appeared that it's not possible with the recent implementation as you need to get the time to wait from the previous response before making the next request. As the limiter neither gets access to the request nor the response it's not possible without forking the whole project.

**Comment by JKorf** [comment]
I've looked at this before and it's not that easy to implement a threadsafe solution for this. This is also still an open issue on the Binance implementation. (https://github.com/JKorf/Binance.Net/issues/174). 
For now you could create your own implementation for this as the response headers are returned in the WebCallResult.

**Comment by JKorf** [comment]
Rate limiter has been reworked recently and request weights have been added in the Binance library
