### ISSUE TITLE
Change json serializer

### ISSUE THREAD

**Issue by BenyErnest** [JKorf/CryptoExchange.Net#92]
Hi
It would be nice if you could update the json serializer from Newtonsoft.Json to System.Text.Json, since the latter have better performance.
Greets.

**Comment by JKorf** [comment]
Hi, I've had a look at this, but switching is quite a lot of work, requiring a lot of rewritten code. For that reason I don't expect to be doing this any time soon, as the rewards would be small compared to the effort it would take.
