### ISSUE TITLE
Implement LogWriters using Microsoft.Extensions.Logging.Abstractions.ILogger

### ISSUE THREAD

**Issue by mrmartan** [JKorf/CryptoExchange.Net#93]
You can go several ways about this. The most straightforward would be just replacing

```csharp
namespace CryptoExchange.Net.Objects
{
    public class BaseOptions
    {
        public LogVerbosity LogVerbosity { get; set; }
        public List<TextWriter> LogWriters { get; set; }
    }
}
```

with 

```csharp
namespace CryptoExchange.Net.Objects
{
    public class BaseOptions
    {
        public List<Microsoft.Extensions.Logging.ILogger> LogWriters { get; set; }
    }
}
```

The motivation should be clear, i.e. ability to use the standard (ASP).NET Core techniques. The way you have it one has to write adapters (custom LogWriter forwarding to ILogger). Or is there a particular reason not to use the standard .NET abstractions?

**Comment by JKorf** [comment]
This has been implemented in the latest releases
